const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

document.querySelectorAll('[data-scroll]').forEach((button) => button.addEventListener('click', () => $(button.dataset.scroll)?.scrollIntoView({ behavior: 'smooth' })));

const docs = {
  identity: 'https://learn.microsoft.com/en-us/azure/role-based-access-control/overview',
  policy: 'https://learn.microsoft.com/en-us/azure/governance/policy/overview',
  storage: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview',
  blob: 'https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview',
  sas: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview',
  files: 'https://learn.microsoft.com/en-us/azure/storage/files/storage-files-introduction',
  bicep: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview',
  vm: 'https://learn.microsoft.com/en-us/azure/virtual-machines/overview',
  appservice: 'https://learn.microsoft.com/en-us/azure/app-service/overview',
  containers: 'https://learn.microsoft.com/en-us/azure/container-instances/container-instances-overview',
  vnet: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview',
  nsg: 'https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview',
  private: 'https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview',
  lb: 'https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-overview',
  monitor: 'https://learn.microsoft.com/en-us/azure/azure-monitor/overview',
  logs: 'https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-query-overview',
  backup: 'https://learn.microsoft.com/en-us/azure/backup/backup-overview',
  siteRecovery: 'https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-overview'
};

const domains = [
  { number: '01', title: 'Identity & governance', weight: '20–25%', copy: 'Entra objects, RBAC, Policy, subscriptions, locks, tags, budgets, and management groups.', doc: docs.identity },
  { number: '02', title: 'Storage', weight: '15–20%', copy: 'Secure, resilient data with storage accounts, SAS, Blob, Azure Files, lifecycle, and replication.', doc: docs.storage },
  { number: '03', title: 'Compute', weight: '20–25%', copy: 'Deploy and operate VMs, scale sets, containers, App Service, TLS, slots, and automation.', doc: docs.vm },
  { number: '04', title: 'Networking', weight: '15–20%', copy: 'Design connected VNets with NSGs, peering, endpoints, DNS, routes, Bastion, and load balancing.', doc: docs.vnet },
  { number: '05', title: 'Monitor & maintain', weight: '10–15%', copy: 'Turn telemetry into action with Monitor, Network Watcher, Backup, and Site Recovery.', doc: docs.monitor }
];

const plans = {
  30: {
    pace: '60–90 MIN / DAY', label: 'FOCUSED SPRINT', summary: 'Four phases. Learn the control, practice the decision, then simulate the exam.',
    weeks: [
      { title: 'Days 01–07', name: 'Foundation + identity', tasks: ['Review exam format, scoring, and Azure hierarchy', 'Create Entra users/groups; practice RBAC scopes', 'Study Policy, locks, tags, budgets, and management groups'] },
      { title: 'Days 08–14', name: 'Storage + compute', tasks: ['Compare redundancy, SAS, keys, and identity-based access', 'Build the VM/App Service/container decision tree', 'Read Bicep and ARM deployment dependencies'] },
      { title: 'Days 15–21', name: 'Networking + operations', tasks: ['Draw VNets, NSGs, routes, peering, and endpoints', 'Compare DNS and load-balancing choices', 'Query Monitor logs; map Backup vs Site Recovery'] },
      { title: 'Days 22–30', name: 'Scenario sprint', tasks: ['Complete two domain-filtered practice rounds', 'Review traps and build a one-page gap sheet', 'Take a timed mixed test; revisit every miss'] }
    ]
  },
  90: {
    pace: '30–60 MIN / DAY', label: 'STEADY BUILD', summary: 'Twelve weeks with room for repetition: understand, operate, troubleshoot, and test.',
    weeks: [
      { title: 'Weeks 01–03', name: 'Azure + identity', tasks: ['Refresh Azure architecture and resource hierarchy', 'Work through Entra users, groups, licenses, SSPR, and guests', 'Practice RBAC inheritance and Policy evaluation'] },
      { title: 'Weeks 04–06', name: 'Storage + compute', tasks: ['Master storage security, redundancy, tiers, and data protection', 'Compare VM disks, availability, scale sets, and moves', 'Study App Service, containers, slots, TLS, and Bicep'] },
      { title: 'Weeks 07–09', name: 'Networking', tasks: ['Design a hub/spoke VNet with peering and UDRs', 'Drill NSG evaluation, private endpoints, and Bastion', 'Compare DNS, Load Balancer, Application Gateway, and probes'] },
      { title: 'Weeks 10–12', name: 'Operate + exam mode', tasks: ['Build Monitor/KQL, alert, Backup, and Site Recovery notes', 'Complete three mixed practice rounds and all case studies', 'Take two timed simulations; close gaps from explanations'] }
    ]
  }
};

const icon = (name) => `assets/icons/${name}.svg`;
const visuals = {
  hierarchy: `<div class="visual-caption">SCOPE HIERARCHY</div><div class="visual-diagram"><div class="diagram-node"><strong>Management group</strong><small>governance scope</small></div><span class="diagram-arrow">→</span><div class="diagram-node"><strong>Subscription</strong><small>billing + limits</small></div><span class="diagram-arrow">→</span><div class="diagram-node"><strong>Resource group</strong><small>lifecycle boundary</small></div><span class="diagram-arrow">→</span><div class="diagram-node"><strong>Resource</strong><small>target object</small></div></div>`,
  privateEndpoint: `<div class="visual-caption">NAME RESOLUTION + NETWORK PATH</div><div class="visual-diagram"><div class="diagram-boundary"><span class="diagram-label">VNET / APP SUBNET</span><div class="diagram-node"><img src="${icon('virtual-machine')}" alt="Virtual Machine icon" /><strong>App VM</strong><small>10.0.1.4</small></div><span class="diagram-arrow">→</span><div class="diagram-node"><img src="${icon('private-endpoint')}" alt="Private Endpoint icon" /><strong>Private endpoint</strong><small>10.0.2.5</small></div></div><span class="diagram-arrow">→</span><div class="diagram-node"><img src="${icon('storage-account')}" alt="Storage account icon" /><strong>Storage account</strong><small>private link</small></div></div>`,
  nsg: `<div class="visual-caption">EFFECTIVE INBOUND RULES · LOWER PRIORITY NUMBER EVALUATES FIRST</div><table class="visual-table"><thead><tr><th>Priority</th><th>Source</th><th>Port</th><th>Action</th></tr></thead><tbody><tr><td>100</td><td>Internet</td><td>443</td><td>Allow</td></tr><tr><td>110</td><td>10.0.0.0/8</td><td>*</td><td>Deny</td></tr><tr><td>200</td><td>Internet</td><td>*</td><td>Deny</td></tr></tbody></table>`,
  redundancy: `<div class="visual-caption">STORAGE REDUNDANCY SNAPSHOT</div><table class="visual-table"><thead><tr><th>Option</th><th>Copies</th><th>Primary protection</th><th>Secondary region</th></tr></thead><tbody><tr><td>LRS</td><td>3</td><td>Single datacenter</td><td>No</td></tr><tr><td>ZRS</td><td>3</td><td>Across zones</td><td>No</td></tr><tr><td>GRS</td><td>6</td><td>Single region</td><td>Async</td></tr><tr><td>GZRS</td><td>6</td><td>Across zones</td><td>Async</td></tr></tbody></table>`,
  appService: `<div class="visual-caption">APP SERVICE RELEASE PATH</div><div class="visual-diagram"><div class="diagram-node"><img src="${icon('app-service')}" alt="App Service icon" /><strong>Slot: staging</strong><small>version 2</small></div><span class="diagram-arrow">⇄</span><div class="diagram-node"><img src="${icon('app-service')}" alt="App Service icon" /><strong>Slot: production</strong><small>version 1</small></div></div>`,
  monitor: `<div class="visual-caption">TELEMETRY → DECISION → ACTION</div><div class="icon-decision-row"><div class="icon-decision"><img src="${icon('azure-monitor')}" alt="Azure Monitor icon" /><b>Metric / log</b><small>CPU > 80% for 10m</small></div><div class="diagram-arrow">→</div><div class="icon-decision"><img src="${icon('azure-monitor')}" alt="Azure Monitor alert icon" /><b>Alert rule</b><small>evaluate condition</small></div><div class="diagram-arrow">→</div><div class="icon-decision"><img src="${icon('recovery-services-vault')}" alt="Recovery Services vault icon" /><b>Action group</b><small>notify on-call</small></div></div>`
};

const questions = [
  { id: 1, domain: 'identity', q: 'You need to give a team read-only access to every resource in one resource group, but no access to other groups. Which role and scope should you use?', opts: ['Reader at the resource-group scope', 'Contributor at the subscription scope', 'Owner at the resource scope', 'User Access Administrator at the management-group scope'], answer: [0], explain: '<strong>Reader at the resource-group scope</strong> grants read access to resources in that group and inherits downward without granting changes.', source: docs.identity },
  { id: 2, domain: 'identity', tag: 'trap', q: 'A user can open a storage account in the portal but cannot list blobs. Which distinction best explains this?', opts: ['Portal access is always equivalent to blob data access', 'Management-plane RBAC and data-plane permissions are separate', 'The storage account must be in the same region as the user', 'The user needs a resource lock removed'], answer: [1], explain: '<strong>Management-plane RBAC and data-plane permissions are separate.</strong> A role such as Reader can inspect the resource while a Blob Data Reader role is needed to read blob contents.', source: docs.identity },
  { id: 3, domain: 'identity', q: 'Which identity type is intended for an application that needs to access Azure resources without storing credentials?', opts: ['Managed identity', 'Guest user', 'Distribution group', 'Resource lock'], answer: [0], explain: '<strong>Managed identity</strong> lets Azure manage the service principal credentials and works with Microsoft Entra authentication.', source: 'https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview' },
  { id: 4, domain: 'identity', tag: 'case', scenario: 'Contoso has a central platform subscription and three application subscriptions. Security requires that every storage account disallow public network access. Application teams must still deploy resources.', q: 'What should the administrator use to enforce the storage network requirement across all three subscriptions?', opts: ['An Azure Policy assignment at a management group', 'A resource lock on each storage account', 'A Reader role at the platform subscription', 'A tag named publicNetworkAccess=false'], answer: [0], explain: '<strong>An Azure Policy assignment at a management group</strong> can evaluate and deny or audit configurations across descendant subscriptions. Tags and locks do not enforce property values.', source: docs.policy },
  { id: 5, domain: 'identity', q: 'Which feature prevents accidental deletion of a resource while still allowing authorized configuration changes?', opts: ['CanNotDelete resource lock', 'ReadOnly resource lock', 'Azure Policy audit effect', 'Reader role'], answer: [0], explain: 'A <strong>CanNotDelete</strong> lock prevents deletion while allowing writes. ReadOnly would also block configuration changes.', source: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources' },
  { id: 6, domain: 'identity', q: 'Which Azure hierarchy level is designed to organize subscriptions and apply governance across them?', opts: ['Management group', 'Availability set', 'Resource group', 'Virtual network'], answer: [0], explain: 'A <strong>management group</strong> sits above subscriptions and provides a scope for policy and RBAC inheritance.', source: 'https://learn.microsoft.com/en-us/azure/governance/management-groups/overview' },
  { id: 7, domain: 'identity', q: 'A company wants to require a cost-center tag on new resources but allow deployments to continue while compliance is measured. Which Policy effect fits?', opts: ['Audit', 'Deny', 'DeployIfNotExists', 'Disabled'], answer: [0], explain: '<strong>Audit</strong> records noncompliant resources without blocking the deployment. Deny would enforce the requirement immediately.', source: docs.policy },
  { id: 8, domain: 'identity', tag: 'trap', q: 'A budget alert has fired. What does that alert do by itself?', opts: ['Stops all resources in the subscription', 'Deletes the most expensive resource', 'Notifies configured recipients; it does not automatically stop spending', 'Changes the subscription to free tier'], answer: [2], explain: 'A budget alert <strong>notifies configured recipients</strong>. It is not an automatic spending cap or shutdown mechanism.', source: 'https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/tutorial-acm-create-budgets' },
  { id: 9, domain: 'identity', q: 'What is the least-privilege role for assigning roles to other principals without managing all resources?', opts: ['User Access Administrator', 'Reader', 'Storage Account Contributor', 'Billing Reader'], answer: [0], explain: '<strong>User Access Administrator</strong> manages access assignments. It is distinct from a resource-management role such as Contributor.', source: docs.identity },
  { id: 10, domain: 'identity', tag: 'case', scenario: 'A contractor from another organization needs temporary access to review a resource group. The contractor must sign in with their existing organization account.', q: 'Which object should you invite to the tenant?', opts: ['A Microsoft Entra B2B guest user', 'A managed identity', 'A service principal with a client secret', 'A dynamic device group'], answer: [0], explain: 'A <strong>Microsoft Entra B2B guest user</strong> can authenticate with the external organization while receiving scoped access in your tenant.', source: 'https://learn.microsoft.com/en-us/entra/external-id/what-is-b2b' },
  { id: 11, domain: 'identity', q: 'Which feature allows users to reset their own passwords after verification?', opts: ['Self-service password reset (SSPR)', 'Azure Advisor', 'Azure Bastion', 'Resource Graph'], answer: [0], explain: '<strong>SSPR</strong> lets users reset or change passwords after the configured authentication methods and licensing requirements are satisfied.', source: 'https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-howitworks' },
  { id: 12, domain: 'identity', tag: 'trap', q: 'A role assigned at the subscription scope normally applies to which resources?', opts: ['Only the subscription object', 'All descendant resource groups and resources', 'Only resources created after the assignment', 'Only Microsoft Entra objects'], answer: [1], explain: 'RBAC assignments <strong>inherit down the hierarchy</strong> from subscription to resource groups and resources unless a more specific restriction applies.', source: docs.identity },

  { id: 13, domain: 'storage', q: 'Which storage redundancy option replicates synchronously across availability zones in the primary region?', opts: ['ZRS', 'LRS', 'GRS', 'RA-GRS'], answer: [0], explain: '<strong>ZRS</strong> synchronously replicates data across availability zones in the primary region. GRS adds asynchronous replication to a secondary region.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy' },
  { id: 14, domain: 'storage', tag: 'trap', q: 'Which credential is most appropriate when an application needs time-limited, narrow access to a container?', opts: ['Account key shared indefinitely', 'A SAS token scoped to the container with required permissions and expiry', 'The subscription owner role', 'A resource lock'], answer: [1], explain: 'A <strong>scoped SAS token</strong> limits resource, permissions, and time. Account keys are broad credentials and should not be distributed to applications.', source: docs.sas },
  { id: 15, domain: 'storage', q: 'Which Blob access tier is intended for data that is rarely accessed but must be available online with lower storage cost?', opts: ['Hot', 'Cool', 'Archive', 'Premium page blob'], answer: [1], explain: '<strong>Cool</strong> is an online tier for infrequently accessed data. Archive has offline rehydration latency and different access economics.', source: docs.blob },
  { id: 16, domain: 'storage', tag: 'case', scenario: 'An analytics team stores raw logs. Files older than 90 days should move to Cool, older than 365 days should be deleted, and the team does not want a scheduled script.', q: 'Which Azure capability should implement this requirement?', opts: ['Blob lifecycle management policy', 'Azure File Sync', 'A storage account firewall rule', 'A recovery plan'], answer: [0], explain: '<strong>Blob lifecycle management</strong> applies rule-based tiering and deletion to blob data based on age and other conditions.', source: 'https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview' },
  { id: 17, domain: 'storage', q: 'Which tool is designed to copy data to and from Azure Storage from the command line with high performance?', opts: ['AzCopy', 'Azure Policy', 'Azure Migrate', 'Network Watcher'], answer: [0], explain: '<strong>AzCopy</strong> is the command-line utility for copying blobs and files to or from Azure Storage.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10' },
  { id: 18, domain: 'storage', q: 'What does blob versioning primarily provide?', opts: ['A history of blob versions that can be accessed or restored', 'A private endpoint for the storage account', 'Synchronous cross-region replication', 'A replacement for authorization'], answer: [0], explain: '<strong>Blob versioning</strong> automatically preserves prior versions when a blob is modified or deleted, supporting recovery and tracking.', source: 'https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview' },
  { id: 19, domain: 'storage', tag: 'trap', q: 'Which statement about a storage account firewall is correct?', opts: ['It grants a user permission to read blob data', 'It restricts network access; identity or token authorization is still required', 'It encrypts every blob with a customer-managed key', 'It replaces private endpoints'], answer: [1], explain: 'A firewall controls <strong>network reachability</strong>. Authorization is a separate concern handled by Entra roles, SAS, or keys.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-network-security' },
  { id: 20, domain: 'storage', q: 'Which service provides SMB file shares that can be mounted by Azure and on-premises clients?', opts: ['Azure Files', 'Blob Storage', 'Table Storage', 'Queue Storage'], answer: [0], explain: '<strong>Azure Files</strong> provides managed file shares over SMB (and NFS for supported configurations).', source: docs.files },
  { id: 21, domain: 'storage', tag: 'case', scenario: 'A web app should access one blob for 15 minutes. It must not know the storage account key and must not write other blobs.', q: 'Which design best meets the requirement?', opts: ['Use a user delegation SAS with read permission, blob scope, and a 15-minute expiry', 'Use the storage account key in an app setting', 'Assign Owner at the subscription scope', 'Make the container public'], answer: [0], explain: 'A <strong>user delegation SAS</strong> avoids account keys and can constrain the token to one blob, read-only, for a short period.', source: docs.sas },
  { id: 22, domain: 'storage', q: 'Which option protects a file share from accidental deletion by retaining deleted files for a configured period?', opts: ['Azure Files soft delete', 'Blob index tags', 'Object replication', 'Storage Explorer'], answer: [0], explain: '<strong>Azure Files soft delete</strong> retains deleted shares for recovery during the configured retention period.', source: 'https://learn.microsoft.com/en-us/azure/storage/files/storage-files-recovery' },
  { id: 23, domain: 'storage', q: 'What is the primary purpose of object replication for Blob Storage?', opts: ['Asynchronously replicate block blobs between storage accounts', 'Provide an SMB mount point', 'Force all writes through a private endpoint', 'Convert blobs to archive tier'], answer: [0], explain: '<strong>Object replication</strong> asynchronously copies block blobs between a source and destination account according to replication rules.', source: 'https://learn.microsoft.com/en-us/azure/storage/blobs/object-replication-overview' },
  { id: 24, domain: 'storage', tag: 'trap', q: 'Which statement correctly distinguishes a stored access policy from a SAS?', opts: ['A stored access policy is only available for the subscription', 'A stored access policy can centralize constraints for certain service SAS tokens', 'A SAS always grants full account access', 'A stored access policy encrypts the storage account'], answer: [1], explain: 'A <strong>stored access policy</strong> can define or revoke shared constraints for supported service SAS tokens at the container or share level.', source: docs.sas },

  { id: 25, domain: 'compute', q: 'Which deployment artifact is the Azure-native, declarative language that compiles to ARM templates?', opts: ['Bicep', 'KQL', 'YAML pipeline only', 'PowerShell DSC'], answer: [0], explain: '<strong>Bicep</strong> is a declarative language for Azure resource deployment and compiles to ARM template JSON.', source: docs.bicep },
  { id: 26, domain: 'compute', tag: 'trap', q: 'What is the key distinction between an availability zone and an availability set?', opts: ['Zones are separate physical locations within a region; sets distribute VMs across fault and update domains', 'Sets always span regions; zones never do', 'Zones are a billing scope; sets are an RBAC scope', 'They are interchangeable names for the same feature'], answer: [0], explain: '<strong>Availability zones</strong> are physically separate datacenters in a region. Availability sets distribute VMs within a datacenter across fault and update domains.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machines/availability' },
  { id: 27, domain: 'compute', q: 'Which disk type is the default OS disk option for most general-purpose Azure VMs?', opts: ['Managed disk', 'Ephemeral local cache only', 'Azure Files share', 'Blob container'], answer: [0], explain: '<strong>Managed disks</strong> are Azure-managed virtual disks used by VMs and available in several performance tiers.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview' },
  { id: 28, domain: 'compute', tag: 'case', scenario: 'A stateless API has variable demand. It should scale horizontally based on CPU and deploy a new version gradually without new infrastructure.', q: 'Which combination is most appropriate?', opts: ['App Service autoscale and a deployment slot', 'A single VM and an availability set', 'Azure Files snapshots and a SAS token', 'A Recovery Services vault and a UDR'], answer: [0], explain: '<strong>App Service autoscale and a deployment slot</strong> address horizontal scaling and controlled version rollout for an App Service app.', source: docs.appservice },
  { id: 29, domain: 'compute', q: 'What does changing a VM size generally change?', opts: ['The VM compute capacity and available attached data-disk limits', 'The tenant directory and RBAC assignments', 'The region of the VM automatically', 'The contents of the OS disk'], answer: [0], explain: 'Changing VM size changes <strong>compute capacity</strong> such as CPU and memory and may affect disk/network limits; it does not move or rewrite the OS disk.', source: docs.vm },
  { id: 30, domain: 'compute', q: 'Which service is optimized for running a single container or small container group without managing VMs?', opts: ['Azure Container Instances', 'Azure Virtual Desktop', 'Azure DNS', 'Azure Load Testing'], answer: [0], explain: '<strong>Azure Container Instances</strong> provides serverless container execution without VM management.', source: docs.containers },
  { id: 31, domain: 'compute', tag: 'trap', q: 'An App Service plan is scaled up. What does that mean?', opts: ['Changing the pricing tier or instance size/capabilities', 'Adding more instances only', 'Creating a new deployment slot', 'Moving the app to another subscription'], answer: [0], explain: '<strong>Scale up</strong> changes the plan tier or instance size. Scale out adds instances.', source: docs.appservice },
  { id: 32, domain: 'compute', tag: 'case', scenario: 'A team needs to deploy the same network, storage, and app resources repeatedly with parameterized names and SKU values.', q: 'Which approach best supports repeatable declarative deployments?', opts: ['A Bicep file with parameters and modules', 'Manual portal clicks recorded in a document', 'A storage SAS token', 'A Network Security Group rule'], answer: [0], explain: '<strong>Bicep with parameters and modules</strong> expresses repeatable infrastructure and keeps environment-specific values separate from resource definitions.', source: docs.bicep },
  { id: 33, domain: 'compute', q: 'What is the purpose of a VM Scale Set?', opts: ['Manage and autoscale a group of load-balanced VMs', 'Store multiple copies of a blob', 'Provide DNS name resolution', 'Assign Entra licenses'], answer: [0], explain: 'A <strong>VM Scale Set</strong> manages a set of load-balanced, similarly configured VMs and can scale the instance count.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview' },
  { id: 34, domain: 'compute', q: 'Which App Service feature lets you validate a release in an isolated environment and swap it into production?', opts: ['Deployment slot', 'App Service plan', 'Access restriction rule', 'Custom domain'], answer: [0], explain: 'A <strong>deployment slot</strong> provides a separate app instance for testing and supports swapping into production.', source: docs.appservice },
  { id: 35, domain: 'compute', tag: 'trap', q: 'Which statement about moving an Azure resource is safest?', opts: ['Every resource can move across subscriptions and regions', 'Move support is resource-specific; region moves often require a different migration pattern', 'A resource lock makes a move possible', 'Changing a tag moves the resource'], answer: [1], explain: '<strong>Move support is resource-specific.</strong> Subscription/resource-group moves have documented dependencies, while regional moves commonly require redeployment or a migration workflow.', source: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription' },
  { id: 36, domain: 'compute', q: 'Which App Service setting maps a custom hostname to an app?', opts: ['Custom domain', 'Deployment slot setting only', 'Private DNS zone link', 'VM extension'], answer: [0], explain: 'The <strong>Custom domain</strong> configuration maps a DNS name to an App Service and can be paired with a certificate for TLS.', source: docs.appservice },

  { id: 37, domain: 'network', q: 'Which resource defines an IP address range and contains subnets?', opts: ['Virtual network', 'Network security group', 'Route table', 'Public IP prefix'], answer: [0], explain: 'A <strong>virtual network</strong> defines the address space and contains one or more subnets.', source: docs.vnet },
  { id: 38, domain: 'network', tag: 'trap', q: 'What is true about VNet peering?', opts: ['It automatically provides transitive routing through a third peered VNet', 'It privately connects VNets, but peering alone is not transitive', 'It requires a public IP on every VM', 'It replaces all NSG rules'], answer: [1], explain: 'VNet peering provides private connectivity, but <strong>peering is not transitive</strong>. A hub may need routing/NVA design for transit.', source: docs.vnet },
  { id: 39, domain: 'network', q: 'Which rule is evaluated first in an NSG?', opts: ['The rule with the lowest priority number', 'The rule with the highest priority number', 'The newest rule', 'The rule closest to the VM in the portal'], answer: [0], explain: 'NSG rules are evaluated in ascending order, so the <strong>lowest priority number</strong> wins when a matching rule is found.', source: docs.nsg },
  { id: 40, domain: 'network', tag: 'case', scenario: 'A PaaS database must be reachable from an application subnet over a private IP. Public internet access must be disabled and the database DNS name should resolve privately.', q: 'Which design meets the requirement?', opts: ['Private endpoint plus a private DNS zone configuration', 'Service endpoint only with a public IP', 'A public Load Balancer in front of the database', 'A UDR that points to the internet'], answer: [0], explain: 'A <strong>private endpoint plus private DNS</strong> gives the PaaS resource a private IP and ensures the normal name resolves to that private address.', source: docs.private },
  { id: 41, domain: 'network', q: 'What does a user-defined route (UDR) allow you to control?', opts: ['The next hop for traffic in a subnet', 'The DNS record TTL for a zone', 'The number of VM instances', 'The blob access tier'], answer: [0], explain: 'A route table with <strong>UDRs</strong> can direct subnet traffic to a virtual appliance, virtual network gateway, internet, or another supported next hop.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-udr-overview' },
  { id: 42, domain: 'network', tag: 'trap', q: 'Which statement about service endpoints is correct?', opts: ['They give a PaaS service a private IP in your subnet', 'They extend a subnet identity to an Azure service and keep the service public endpoint', 'They are required for VNet peering', 'They encrypt all application payloads'], answer: [1], explain: 'A <strong>service endpoint</strong> enables subnet-based access to supported Azure services while the service endpoint remains public. A private endpoint uses a private IP.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview' },
  { id: 43, domain: 'network', q: 'Which Azure service provides managed RDP/SSH access to VMs without requiring public IPs on the VMs?', opts: ['Azure Bastion', 'Azure DNS', 'Azure Front Door', 'Azure Firewall Manager only'], answer: [0], explain: '<strong>Azure Bastion</strong> provides browser-based RDP/SSH through the Azure portal over TLS, allowing VMs to remain without public IPs.', source: 'https://learn.microsoft.com/en-us/azure/bastion/bastion-overview' },
  { id: 44, domain: 'network', tag: 'case', scenario: 'Two web VMs sit behind an internal load balancer. One VM is never receiving traffic. The backend pool is configured, but the health probe marks that VM unhealthy.', q: 'What should you inspect first?', opts: ['The probe protocol/port/path and whether the VM permits the probe', 'The storage account access tier', 'The Entra license assignment', 'The App Service deployment slot'], answer: [0], explain: 'A load balancer only sends new flows to healthy backends, so inspect the <strong>probe settings and backend response</strong>, plus NSG/firewall rules.', source: docs.lb },
  { id: 45, domain: 'network', q: 'Which service resolves names for Azure resources using a Microsoft-managed DNS service by default?', opts: ['Azure-provided DNS', 'Azure Backup', 'Application Gateway WAF', 'Azure Policy'], answer: [0], explain: '<strong>Azure-provided DNS</strong> is the default name-resolution service for VMs in a VNet; custom DNS can be configured when needed.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances' },
  { id: 46, domain: 'network', q: 'What is an application security group (ASG) primarily used for?', opts: ['Grouping VM network interfaces so NSG rules can express application roles', 'Storing TLS certificates', 'Replicating VNets across regions', 'Managing Azure subscriptions'], answer: [0], explain: 'An <strong>ASG</strong> groups network interfaces by application role, making NSG rules easier to read and maintain.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/application-security-groups' },
  { id: 47, domain: 'network', tag: 'trap', q: 'When evaluating effective NSG rules for a VM, what should you remember?', opts: ['Only the subnet NSG matters', 'Only the NIC NSG matters', 'Inbound rules can be affected by both subnet and NIC NSGs', 'NSGs are evaluated after the application receives traffic'], answer: [2], explain: 'For a VM, <strong>subnet and NIC NSGs</strong> both participate in the effective rule set. A deny at either applicable layer can block traffic.', source: docs.nsg },
  { id: 48, domain: 'network', q: 'Which load-balancing option operates at Layer 7 and can route HTTP traffic using URL paths?', opts: ['Application Gateway', 'Azure Load Balancer', 'VNet peering', 'NAT Gateway'], answer: [0], explain: '<strong>Application Gateway</strong> is a Layer 7 HTTP(S) load balancer with path-based routing. Azure Load Balancer is Layer 4.', source: 'https://learn.microsoft.com/en-us/azure/application-gateway/overview' },

  { id: 49, domain: 'monitor', q: 'Which Azure Monitor data type is best for a time-series value such as VM CPU percentage?', opts: ['Metric', 'Activity log only', 'Resource lock', 'Management group'], answer: [0], explain: 'A <strong>metric</strong> is a time-series numerical measurement such as CPU percentage and is suited to near-real-time alerting.', source: docs.monitor },
  { id: 50, domain: 'monitor', tag: 'trap', q: 'Which statement correctly distinguishes Azure metrics from logs?', opts: ['Metrics are numeric time-series; logs are richer event and text records queried in Log Analytics', 'Logs are always cheaper and real-time; metrics cannot alert', 'Metrics contain full queryable stack traces by default', 'They are two names for the same data'], answer: [0], explain: '<strong>Metrics are numeric time-series</strong>; logs provide richer records for analysis with KQL. Both can drive alerts, but their data and use cases differ.', source: docs.monitor },
  { id: 51, domain: 'monitor', q: 'Where are KQL queries commonly used to analyze Azure Monitor logs?', opts: ['A Log Analytics workspace', 'A resource lock', 'An availability set', 'A storage access key blade'], answer: [0], explain: 'Azure Monitor logs are queried in a <strong>Log Analytics workspace</strong> using Kusto Query Language (KQL).', source: docs.logs },
  { id: 52, domain: 'monitor', tag: 'case', scenario: 'An operations team wants a single notification when a production VM has high CPU for 10 minutes. The email should go to the on-call group.', q: 'Which configuration should you create?', opts: ['Metric alert with a condition, action group, and appropriate evaluation window', 'Resource lock with a CanNotDelete setting', 'A storage lifecycle rule', 'A user-defined route'], answer: [0], explain: 'A <strong>metric alert plus action group</strong> evaluates the CPU condition and sends the notification to the on-call recipients.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-overview' },
  { id: 53, domain: 'monitor', q: 'What is an action group?', opts: ['A reusable collection of notification and automation actions for alerts', 'A group of VMs in an availability set', 'A set of RBAC roles', 'A collection of storage containers'], answer: [0], explain: 'An <strong>action group</strong> centralizes actions such as email, SMS, webhook, Logic App, or automation runbook for alert rules.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/action-groups' },
  { id: 54, domain: 'monitor', tag: 'trap', q: 'Which service is intended to restore backed-up data after accidental deletion, while Site Recovery primarily addresses what scenario?', opts: ['Backup restores data; Site Recovery orchestrates disaster recovery/failover', 'Backup changes NSG priorities; Site Recovery manages RBAC', 'Backup provides DNS; Site Recovery provides SAS', 'They are identical services'], answer: [0], explain: '<strong>Azure Backup</strong> protects and restores data. <strong>Site Recovery</strong> orchestrates replication and failover for business continuity.', source: docs.backup },
  { id: 55, domain: 'monitor', q: 'What is the purpose of a Recovery Services vault?', opts: ['Store backup data and recovery points for supported workloads', 'Host a VNet subnet', 'Issue Entra tokens', 'Route internet traffic'], answer: [0], explain: 'A <strong>Recovery Services vault</strong> stores backup data and recovery points for supported Azure Backup and Site Recovery scenarios.', source: docs.backup },
  { id: 56, domain: 'monitor', tag: 'case', scenario: 'A regional outage affects an Azure VM. The business has a recovery plan that replicates the VM to a secondary region and has tested failover.', q: 'Which operation should the administrator perform to bring the workload up in the secondary region?', opts: ['Fail over the protected item in Azure Site Recovery', 'Restore a deleted blob version', 'Change the VM availability set', 'Run a storage lifecycle policy'], answer: [0], explain: 'A configured Site Recovery plan uses <strong>failover</strong> to activate the replicated workload in the secondary region.', source: docs.siteRecovery },
  { id: 57, domain: 'monitor', q: 'Which Network Watcher capability helps test whether a VM can reach a destination on a specific port?', opts: ['Connection troubleshoot', 'Blob inventory', 'Cost analysis', 'Access reviews'], answer: [0], explain: '<strong>Connection troubleshoot</strong> tests connectivity between a source and destination and helps identify the failing component.', source: 'https://learn.microsoft.com/en-us/azure/network-watcher/connection-troubleshoot-overview' },
  { id: 58, domain: 'monitor', q: 'Which Azure Monitor feature provides curated telemetry for services such as VMs and storage accounts?', opts: ['Insights', 'Resource locks', 'Management groups', 'SAS'], answer: [0], explain: '<strong>Insights</strong> provide curated monitoring views and telemetry for supported Azure resources.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-overview' },
  { id: 59, domain: 'monitor', tag: 'trap', q: 'A log alert has a query that returns no rows. What is the most useful first check?', opts: ['Verify the resource is sending the relevant category to the workspace and the query time range is correct', 'Add an Owner role to every user', 'Change the VM size', 'Create a resource lock'], answer: [0], explain: 'Start with telemetry plumbing: <strong>diagnostic settings, destination workspace, table/category, and time range</strong>. An empty query cannot trigger the intended condition.', source: docs.logs },
  { id: 60, domain: 'monitor', tag: 'case', scenario: 'You need a weekly view of backup failures across several vaults and want the data retained for analysis rather than relying only on individual alert emails.', q: 'Which approach is most appropriate?', opts: ['Configure backup reporting/diagnostics and analyze the collected data in the reporting destination', 'Use a ReadOnly lock on each vault', 'Create a public IP for each vault', 'Move all vaults into one resource group'], answer: [0], explain: 'Centralized <strong>backup reporting and diagnostic data</strong> supports cross-vault analysis and retention beyond individual notifications.', source: 'https://learn.microsoft.com/en-us/azure/backup/monitor-azure-backup-with-azure-monitor' },

  { id: 61, domain: 'identity', visual: visuals.hierarchy, q: 'A role assignment is made at the subscription scope. Which descendant is normally affected?', opts: ['A resource group and its resources', 'Only the management group above it', 'Only a newly created Entra user', 'No descendant until each resource is tagged'], answer: [0], explain: 'RBAC assignments normally <strong>inherit from the chosen scope to descendants</strong>. Tags do not control authorization inheritance.', source: docs.identity },
  { id: 62, domain: 'identity', tag: 'case', scenario: 'A platform team wants an Azure Policy definition to add a missing tag automatically when a resource is created. The managed identity used by the policy must be able to modify the resource.', q: 'Which Policy effect and implementation detail are required?', opts: ['DeployIfNotExists or Modify, with a managed identity granted the required permissions', 'Audit, with no identity because audit changes resources', 'Deny, with a Reader role assigned to the policy', 'Disabled, with a CanNotDelete lock'], answer: [0], explain: '<strong>DeployIfNotExists or Modify</strong> can remediate configuration, and the policy assignment needs a managed identity with permission to make that change.', source: docs.policy },
  { id: 63, domain: 'identity', tag: 'trap', q: 'Which statement about a resource group is most accurate?', opts: ['It is a lifecycle and management container; resources can have dependencies in other groups', 'It is a hard security boundary that prevents all cross-group communication', 'It can contain resources from multiple tenants', 'It is the same thing as a subscription'], answer: [0], explain: 'A <strong>resource group</strong> organizes resources for lifecycle and management. It is not a network or tenant isolation boundary.', source: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups' },
  { id: 64, domain: 'identity', visual: visuals.hierarchy, q: 'Which scope is the narrowest choice for granting a deployment team access to exactly one storage account?', opts: ['The storage account resource', 'The management group', 'The tenant root', 'All subscriptions in the tenant'], answer: [0], explain: 'Choose the <strong>storage account resource scope</strong> for the narrowest assignment. A broader scope would grant unnecessary access.', source: docs.identity },

  { id: 65, domain: 'storage', visual: visuals.redundancy, tag: 'case', scenario: 'A storage account must remain available if one availability zone fails. The organization does not require protection from a full regional outage for this workload.', q: 'Which redundancy option is the most targeted fit?', opts: ['ZRS', 'LRS', 'GRS', 'Archive tier'], answer: [0], explain: '<strong>ZRS</strong> synchronously replicates data across availability zones in the primary region. GRS adds a secondary region and is beyond the stated requirement.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy' },
  { id: 66, domain: 'storage', tag: 'trap', q: 'Which feature is designed to reduce the impact of an accidentally deleted blob?', opts: ['Blob soft delete', 'Storage firewall', 'Private DNS zone', 'Access key rotation'], answer: [0], explain: '<strong>Blob soft delete</strong> retains deleted blobs for a configured period. Firewalls and key rotation address access, not recovery.', source: 'https://learn.microsoft.com/en-us/azure/storage/blobs/soft-delete-blob-overview' },
  { id: 67, domain: 'storage', visual: visuals.privateEndpoint, q: 'In the diagram, which control makes the storage account reachable through the private IP rather than its public endpoint?', opts: ['Private endpoint plus the storage account network configuration', 'A blob lifecycle policy', 'A stored access policy only', 'A storage access tier'], answer: [0], explain: 'The <strong>private endpoint</strong> creates a network interface with a private IP. DNS must also resolve the service name to that private endpoint.', source: docs.private },
  { id: 68, domain: 'storage', q: 'Which authorization option lets Azure Files use Microsoft Entra identities for share-level access control?', opts: ['Identity-based authentication for Azure Files', 'Anonymous public access', 'A blob index tag', 'Archive rehydration'], answer: [0], explain: '<strong>Identity-based authentication</strong> integrates Azure Files with identity providers so share and directory permissions can be evaluated for users or groups.', source: docs.files },

  { id: 69, domain: 'compute', visual: visuals.appService, q: 'A release has been validated in staging and should receive production traffic with minimal interruption. What should you do?', opts: ['Swap the staging slot with production', 'Resize the storage account', 'Move the app to another resource group', 'Create a new VNet peering'], answer: [0], explain: 'A <strong>slot swap</strong> moves the validated deployment into production while preserving the slot model for rollback and testing.', source: docs.appservice },
  { id: 70, domain: 'compute', tag: 'trap', q: 'Which service is the best fit for a long-running application that needs OS-level control and custom VM extensions?', opts: ['Azure Virtual Machines', 'Azure Container Instances', 'Azure Blob Storage', 'Azure Monitor Workbooks'], answer: [0], explain: '<strong>Azure Virtual Machines</strong> provide OS-level control and support VM extensions. Container Instances abstract away the VM layer.', source: docs.vm },
  { id: 71, domain: 'compute', visual: visuals.appService, q: 'Which setting is commonly marked as a deployment slot setting so it stays with the slot during a swap?', opts: ['A secret or connection string that is environment-specific', 'The app’s source code package', 'The slot name itself', 'The resource group name'], answer: [0], explain: 'Environment-specific <strong>app settings and connection strings</strong> can be marked as slot settings so they remain with the slot during a swap.', source: 'https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots' },
  { id: 72, domain: 'compute', tag: 'case', scenario: 'A container image is stored privately. A container workload must pull it without embedding a registry password in its command line.', q: 'Which Azure service and authentication pattern should you consider?', opts: ['Azure Container Registry with a managed identity or appropriate registry credentials', 'Azure DNS with a public TXT record', 'A resource lock on the image', 'A blob lifecycle rule'], answer: [0], explain: 'A private <strong>Azure Container Registry</strong> can be accessed by a workload using a managed identity or scoped registry authentication, avoiding hard-coded secrets.', source: 'https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication' },

  { id: 73, domain: 'network', visual: visuals.nsg, q: 'Based on the rules shown, what happens to inbound HTTPS traffic from the internet?', opts: ['It is allowed by priority 100', 'It is denied by priority 110', 'It is denied by priority 200', 'It is allowed only after the default rule'], answer: [0], explain: 'The traffic matches the <strong>priority 100 allow for Internet on port 443</strong> first. NSG processing stops at the first matching rule.', source: docs.nsg },
  { id: 74, domain: 'network', tag: 'case', scenario: 'A hub VNet contains a network virtual appliance. A spoke subnet must send internet-bound traffic through that appliance, while traffic to the appliance itself must remain reachable.', q: 'Which configuration is required in the spoke?', opts: ['A route table with a 0.0.0.0/0 UDR pointing to the virtual appliance', 'A private endpoint on the appliance', 'A blob SAS token', 'A ReadOnly resource lock'], answer: [0], explain: 'A <strong>0.0.0.0/0 UDR</strong> with the appliance as next hop directs default traffic through the intended inspection path.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-udr-overview' },
  { id: 75, domain: 'network', visual: visuals.privateEndpoint, tag: 'trap', q: 'Which statement best describes the DNS responsibility in the diagram?', opts: ['Private DNS must resolve the service hostname to the private endpoint IP for transparent access', 'DNS is unrelated because private endpoints use only IP literals', 'The public DNS record must be deleted from Microsoft', 'An NSG automatically creates the private DNS record'], answer: [0], explain: 'Private endpoint designs commonly use a <strong>private DNS zone</strong> so the normal service hostname resolves to the private IP from inside the VNet.', source: 'https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns' },
  { id: 76, domain: 'network', tag: 'trap', q: 'A subnet has an NSG that allows TCP 443 inbound, but a VM NIC has an NSG that denies TCP 443 inbound. What is the likely effective result?', opts: ['The connection is denied', 'The connection is allowed because subnet rules always win', 'The connection is allowed because an allow anywhere overrides a deny', 'The result depends only on the VM size'], answer: [0], explain: 'Both subnet and NIC NSGs contribute to the effective rules. A matching <strong>deny at the NIC layer</strong> can block the connection.', source: docs.nsg },

  { id: 77, domain: 'monitor', visual: visuals.monitor, q: 'Which component in the visual should contain the email or webhook destination?', opts: ['Action group', 'Metric namespace', 'Log Analytics table', 'Recovery point'], answer: [0], explain: 'An <strong>action group</strong> contains reusable notification and automation destinations invoked by an alert rule.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/action-groups' },
  { id: 78, domain: 'monitor', tag: 'case', scenario: 'A VM team wants a dashboard showing CPU trends for the last 30 days and a queryable list of failed sign-in events from connected services.', q: 'Which pairing best fits the two needs?', opts: ['Metrics for CPU trends and Log Analytics logs for queryable events', 'Activity log for CPU trends and a SAS token for sign-ins', 'RBAC for CPU trends and a resource lock for events', 'A backup vault for both'], answer: [0], explain: '<strong>Metrics</strong> are suited to numerical time series, while <strong>Log Analytics logs</strong> support rich querying of collected records.', source: docs.monitor },
  { id: 79, domain: 'monitor', tag: 'trap', q: 'Which statement about an Azure Activity Log is correct?', opts: ['It records subscription-level control-plane operations such as resource creation and deletion', 'It captures every guest OS process automatically', 'It is the same as a VM metric', 'It stores blob contents for recovery'], answer: [0], explain: 'The <strong>Activity Log</strong> records control-plane operations at the subscription level, such as create, update, and delete actions.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log' },
  { id: 80, domain: 'monitor', visual: visuals.monitor, tag: 'case', scenario: 'A critical VM must be recoverable after a regional outage. The organization wants a planned test that does not interrupt production and a documented recovery sequence.', q: 'Which capability best addresses this requirement?', opts: ['Azure Site Recovery test failover and a recovery plan', 'Blob versioning and lifecycle management', 'A CanNotDelete lock and a budget alert', 'An NSG and Application Security Group'], answer: [0], explain: '<strong>Site Recovery test failover and recovery plans</strong> support non-disruptive validation of replication and ordered recovery steps.', source: docs.siteRecovery },

  { id: 81, domain: 'identity', difficulty: 'hard', multi: true, visual: visuals.hierarchy, tag: 'case', scenario: 'A platform team assigns Reader at the subscription scope. A separate policy assignment at the management-group scope denies storage accounts that allow public network access. An application owner asks for Contributor on one resource group.', q: 'Which two statements are correct? Select all that apply.', opts: ['The Reader assignment can be inherited by resources in the subscription', 'The application owner can bypass the policy deny because they have Contributor', 'The policy can deny a deployment even when RBAC allows the write', 'The Contributor assignment at a resource group grants access to all subscriptions'], answer: [0,2], explain: 'RBAC and Policy answer different questions: <strong>RBAC grants an authorized action, while Policy can deny a noncompliant resource state</strong>. Both assignments inherit only within their respective scopes.', source: docs.policy },
  { id: 82, domain: 'storage', difficulty: 'hard', multi: true, visual: visuals.privateEndpoint, tag: 'case', scenario: 'A production app must read blobs from a storage account using its managed identity. The account must reject public network traffic, and name resolution must remain transparent to the app.', q: 'Which two controls are required? Select all that apply.', opts: ['A private endpoint and private DNS configuration', 'A storage account access key stored in the app', 'A Microsoft Entra data-plane role for the managed identity', 'A public container with anonymous read access'], answer: [0,2], explain: 'The <strong>private endpoint/private DNS pair</strong> provides the network path, while a <strong>Blob data-plane role</strong> authorizes the managed identity to read content. Neither control replaces the other.', source: docs.private },
  { id: 83, domain: 'compute', difficulty: 'hard', tag: 'case', scenario: 'A stateless web tier must tolerate a zone failure, add instances when CPU is high, and keep all instances on the same VM image version.', q: 'Which design best satisfies all three constraints?', opts: ['A zone-spanning VM Scale Set with autoscale rules and a model/image update strategy', 'One large VM in an availability set with a budget alert', 'Azure Container Instances with a storage lifecycle rule', 'An App Service deployment slot without scaling'], answer: [0], explain: 'A <strong>VM Scale Set</strong> provides uniform instances and autoscaling; zone placement adds zonal resilience. The scale-set model keeps configuration consistent.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-autoscale-portal' },
  { id: 84, domain: 'compute', difficulty: 'hard', visual: visuals.appService, q: 'A Bicep deployment creates a VNet, a private endpoint, and an App Service that depends on the endpoint’s private DNS zone group. What is the safest way to express the deployment order?', opts: ['Use symbolic references/module outputs so Bicep builds an implicit dependency graph', 'Rely on the order of resource declarations in the file only', 'Add a ReadOnly lock before deploying', 'Deploy manually and export a template afterward'], answer: [0], explain: 'Bicep symbolic references and module outputs create <strong>explicit dependency relationships</strong> that ARM can honor. File order alone is not a reliable dependency contract.', source: docs.bicep },
  { id: 85, domain: 'network', difficulty: 'hard', multi: true, tag: 'case', scenario: 'A hub-and-spoke design has peering between the hub and two spokes. An NVA in the hub should inspect spoke-to-internet traffic. The spokes must not rely on automatic transit.', q: 'Which two changes are required in the spoke design? Select all that apply.', opts: ['Associate a route table with a default route to the NVA', 'Assume hub-to-spoke peering automatically gives both spokes transit access', 'Configure the required peering gateway/forwarded-traffic settings for the chosen design', 'Remove all NSGs so the NVA can route traffic'], answer: [0,2], explain: 'The spoke needs a <strong>UDR for the desired next hop</strong>, and the peering/NVA design must explicitly allow the required forwarded traffic or gateway transit. Peering alone is not transitive.', source: docs.vnet },
  { id: 86, domain: 'network', difficulty: 'hard', multi: true, visual: visuals.nsg, tag: 'trap', q: 'An inbound packet matches an allow rule on the subnet NSG but a deny rule on the NIC NSG. Which two conclusions are valid? Select all that apply.', opts: ['The effective result can be denied', 'Both applicable NSGs contribute to the effective security rules', 'The subnet allow always overrides the NIC deny', 'The VM size determines which NSG wins'], answer: [0,1], explain: 'Inbound evaluation considers <strong>both subnet and NIC NSGs</strong>. A matching deny at either applicable layer can prevent the connection.', source: docs.nsg },
  { id: 87, domain: 'monitor', difficulty: 'hard', multi: true, visual: visuals.monitor, scenario: 'A log alert should fire when failed sign-ins for a service exceed a threshold. The relevant diagnostic category is not currently visible in the Log Analytics workspace.', q: 'Which two actions should you take first? Select all that apply.', opts: ['Configure diagnostic settings to send the relevant category to the workspace', 'Verify the query table and time range before tuning the threshold', 'Create a resource lock on the workspace', 'Replace the log alert with a storage SAS token'], answer: [0,1], explain: 'First ensure the data is collected, then validate <strong>table, query, and time range</strong>. Alert logic cannot work against telemetry that is not present or is queried incorrectly.', source: docs.logs },
  { id: 88, domain: 'monitor', difficulty: 'hard', multi: true, tag: 'case', scenario: 'A business-critical VM needs point-in-time file recovery and a regional disaster-recovery plan. Recovery objectives require frequent replication and a defined failover sequence.', q: 'Which two services should be combined? Select all that apply.', opts: ['Azure Backup for recovery points and file restore', 'Azure Site Recovery for replication and orchestrated failover', 'Azure Policy alone for point-in-time recovery', 'Azure Monitor metrics alone for regional recovery'], answer: [0,1], explain: '<strong>Backup</strong> handles data recovery from recovery points; <strong>Site Recovery</strong> handles workload replication, test failover, and regional recovery orchestration.', source: docs.siteRecovery },
  { id: 89, domain: 'identity', difficulty: 'hard', tag: 'case', scenario: 'A regulated subscription requires: no public storage endpoints, a mandatory environment tag, and a deployment team that can update resources but cannot assign permissions.', q: 'Which combination best matches the requirements?', opts: ['Policy deny for public endpoints, Policy modify/audit for the tag, and Contributor at the resource-group scope', 'Owner at management-group scope and a CanNotDelete lock', 'Reader at subscription scope and a public storage endpoint', 'A budget alert, a SAS token, and User Access Administrator'], answer: [0], explain: 'The design combines <strong>Policy for configuration governance</strong> with <strong>Contributor at the narrow resource-group scope</strong>. Contributor does not grant role-assignment authority.', source: docs.policy },
  { id: 90, domain: 'monitor', difficulty: 'hard', tag: 'trap', q: 'A metric alert is evaluated every minute with a five-minute lookback. The requirement is to alert only when CPU is above 80% for five consecutive minutes. Which alert condition most closely matches the intent?', opts: ['Static threshold above 80% with a five-minute evaluation window and appropriate aggregation', 'A single Activity Log event for VM start', 'A monthly cost budget at 80%', 'A log query with no time window'], answer: [0], explain: 'Use a <strong>metric alert with the threshold, aggregation, and evaluation window</strong> aligned to the sustained condition. An Activity Log event and budget measure different signals.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-types' }
];

const flashcards = [
  { domain: 'identity', title: 'RBAC scope inheritance', visual: visuals.hierarchy, definition: 'Access assignments flow down from management group → subscription → resource group → resource.', cue: 'Ask: what is the narrowest scope that satisfies the requirement?', source: docs.identity },
  { domain: 'identity', title: 'Policy and RBAC', visual: `<div class="flash-diagram vertical-flow"><div class="flash-lane"><span class="flash-lane-label">WHO / CAN</span><div class="flash-service"><img src="${icon('entra-managed-identity')}" alt="Microsoft Entra managed identity icon" /><b>RBAC</b><small>authorization</small></div><span class="flash-arrow">↓</span><div class="flash-outcome">permits an action</div></div><div class="flash-lane"><span class="flash-lane-label">WHAT / SHOULD</span><div class="flash-service"><img src="${icon('azure-monitor')}" alt="Azure Policy governance icon" /><b>Azure Policy</b><small>governance</small></div><span class="flash-arrow">↓</span><div class="flash-outcome">audits or denies state</div></div></div>`, definition: 'RBAC controls who can perform actions. Azure Policy evaluates resource state and can audit, deny, or remediate.', cue: 'Contributor does not bypass a Policy deny.', source: docs.policy },
  { domain: 'storage', title: 'Storage redundancy', visual: visuals.redundancy, definition: 'LRS protects within one datacenter; ZRS spans availability zones; GRS/GZRS add asynchronous secondary-region replication.', cue: 'Match the failure domain in the requirement to the replication boundary.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy' },
  { domain: 'storage', title: 'Blob access layers', visual: `<div class="flash-diagram access-stack"><div class="stack-row"><img src="${icon('virtual-network')}" alt="Virtual Network icon" /><b>Network path</b><span>firewall / private endpoint</span></div><div class="stack-row"><img src="${icon('entra-managed-identity')}" alt="Microsoft Entra identity icon" /><b>Identity</b><span>RBAC / managed identity</span></div><div class="stack-row"><img src="${icon('storage-account')}" alt="Storage account icon" /><b>Token</b><span>SAS / key</span></div><div class="stack-row final"><img src="${icon('storage-account')}" alt="Storage data icon" /><b>Data</b><span>Blob / Files</span></div></div>`, definition: 'A successful storage request needs both a reachable network path and a valid authorization method. SAS and keys do not fix a blocked network path.', cue: 'Separate network access from data-plane permission.', source: docs.storage },
  { domain: 'compute', title: 'App Service slot swap', visual: visuals.appService, definition: 'Deploy to staging, validate, then swap staging and production. Slot settings keep environment-specific values with their slot.', cue: 'Scale up changes size/tier; scale out changes instance count.', source: docs.appservice },
  { domain: 'compute', title: 'Availability choices', visual: `<div class="flash-table-wrap"><table class="flash-table"><thead><tr><th>Choice</th><th>Resilience boundary</th><th>Think about</th></tr></thead><tbody><tr><td>Availability set</td><td>Fault/update domains</td><td>VMs in one datacenter</td></tr><tr><td>Availability zone</td><td>Physical zone</td><td>Datacenter-level failure</td></tr><tr><td>VM Scale Set</td><td>Uniform VM group</td><td>Autoscale + consistency</td></tr></tbody></table></div>`, definition: 'Availability sets distribute VMs across fault and update domains. Zones place resources in separate physical locations. Scale sets manage a uniform, scalable fleet.', cue: 'Availability and scaling are separate decisions; a Scale Set can use zones.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machines/availability' },
  { domain: 'network', title: 'Hub-and-spoke transit', visual: `<div class="flash-diagram hub-spoke"><div class="hub-node"><img src="${icon('virtual-network')}" alt="Hub virtual network icon" /><b>Hub VNet</b><small>NVA / gateway</small></div><div class="spoke spoke-a"><img src="${icon('virtual-network')}" alt="Spoke virtual network icon" /><b>Spoke A</b><small>UDR → NVA</small></div><div class="spoke spoke-b"><img src="${icon('virtual-network')}" alt="Spoke virtual network icon" /><b>Spoke B</b><small>UDR → NVA</small></div><div class="hub-line line-a"></div><div class="hub-line line-b"></div></div>`, definition: 'Peering connects VNets privately but is not transitive. Explicit UDRs, gateway transit, or a network virtual appliance are needed for hub-mediated traffic.', cue: 'Connected does not mean transit is automatic.', source: docs.vnet },
  { domain: 'network', title: 'Private vs service endpoint', visual: `<div class="flash-diagram endpoint-compare"><div class="endpoint-card"><img src="${icon('private-endpoint')}" alt="Private Endpoint icon" /><b>Private endpoint</b><small>Private IP in your VNet</small><span>Private Link</span></div><div class="endpoint-card"><img src="${icon('virtual-network')}" alt="Virtual Network service endpoint icon" /><b>Service endpoint</b><small>Public service endpoint</small><span>Subnet identity</span></div></div>`, definition: 'A private endpoint creates a private IP-backed NIC for a PaaS resource. A service endpoint extends subnet identity to a supported public service endpoint.', cue: 'If the prompt says “private IP” or “public access disabled,” start with private endpoint.', source: docs.private },
  { domain: 'network', title: 'NSG evaluation', visual: visuals.nsg, definition: 'Inbound traffic can be constrained by both subnet and NIC NSGs. Matching rules evaluate from lowest priority number upward.', cue: 'A deny at either applicable layer can block the packet.', source: docs.nsg },
  { domain: 'monitor', title: 'Telemetry to action', visual: visuals.monitor, definition: 'Metrics and logs provide signals; alert rules evaluate conditions; action groups notify or automate a response.', cue: 'If a log query returns no rows, check diagnostic settings and workspace routing first.', source: docs.monitor },
  { domain: 'monitor', title: 'Backup vs Site Recovery', visual: `<div class="flash-diagram recovery-compare"><div class="recovery-card"><img src="${icon('recovery-services-vault')}" alt="Recovery Services vault icon" /><b>Azure Backup</b><small>Recovery points</small><span>Restore data</span></div><div class="recovery-card"><img src="${icon('virtual-machine')}" alt="Virtual Machine icon" /><b>Site Recovery</b><small>Replication + plans</small><span>Fail over workload</span></div></div>`, definition: 'Azure Backup protects data and provides restore points. Site Recovery replicates workloads and orchestrates failover to a secondary region.', cue: 'Restore is not failover; choose based on the recovery objective.', source: docs.siteRecovery },
  { domain: 'network', title: 'Load-balancer health', visual: `<div class="flash-diagram load-flow"><div class="diagram-node"><img src="${icon('load-balancer')}" alt="Azure Load Balancer icon" /><strong>Load Balancer</strong><small>probe first</small></div><span class="diagram-arrow">→</span><div class="diagram-node"><img src="${icon('virtual-machine')}" alt="Virtual Machine icon" /><strong>Healthy VM</strong><small>receives flows</small></div><span class="diagram-arrow muted-arrow">×</span><div class="diagram-node faded"><img src="${icon('virtual-machine')}" alt="Virtual Machine icon" /><strong>Unhealthy VM</strong><small>no new flows</small></div></div>`, definition: 'A Load Balancer sends new flows only to healthy backend instances. The probe protocol, port, path, and firewall rules all matter.', cue: 'Backend pool membership alone does not prove a backend can receive traffic.', source: docs.lb }
];

const domainLabels = { identity: 'IDENTITY', storage: 'STORAGE', compute: 'COMPUTE', network: 'NETWORKING', monitor: 'MONITORING' };
const successMessages = {
  identity: ['Correct — you matched scope to the control plane.', 'That’s it — least privilege and governance are aligned.', 'Correct — you separated authorization from policy enforcement.'],
  storage: ['Correct — you chose the right data-protection layer.', 'Exactly — the access path and data permission both fit.', 'Correct — that storage constraint points to this control.'],
  compute: ['Correct — you picked the compute model that fits the workload.', 'Nice work — deployment behavior and scaling are both accounted for.', 'Correct — you read the operational constraint, not just the product name.'],
  network: ['Correct — the traffic path and security boundary line up.', 'Exactly — you followed the route and rule evaluation order.', 'Correct — that is the least-surprising network design.'],
  monitor: ['Correct — the signal, condition, and response are connected.', 'That’s the operational answer — telemetry can now drive action.', 'Correct — you distinguished recovery, monitoring, and alerting.']
};
function correctMessage(item) { const messages = successMessages[item.domain] || ['Correct — well reasoned.']; return messages[item.id % messages.length]; }
$('#all-count').textContent = questions.length;
$('#case-count').textContent = questions.filter((question) => question.tag === 'case').length;
$('#trap-count').textContent = questions.filter((question) => question.tag === 'trap').length;
$('#advanced-count').textContent = questions.filter((question) => question.difficulty === 'hard').length;
const trapCards = [
  ['RBAC vs data access', 'CONTROL PLANE ≠ DATA PLANE', 'Reader can open a resource; it does not automatically read the blobs, files, or secrets inside it. Match the role to the data plane.'],
  ['Policy vs RBAC', 'GOVERNANCE ≠ AUTHORIZATION', 'Policy evaluates resource state and can audit or deny. RBAC answers who may perform an action. They complement each other.'],
  ['Service vs private endpoint', 'PUBLIC ENDPOINT ≠ PRIVATE IP', 'A service endpoint keeps the service public while adding subnet identity. A private endpoint creates a NIC/private IP in your VNet.'],
  ['NSG priority', 'LOW NUMBER WINS', 'Rules are processed from lowest priority number upward. A broad allow placed before a specific deny can change the result.'],
  ['Scale up vs scale out', 'SIZE ≠ INSTANCES', 'Scale up changes the plan or VM size. Scale out adds instances. Look for “capacity” versus “number of copies.”'],
  ['Backup vs Site Recovery', 'RESTORE ≠ FAILOVER', 'Backup restores data from recovery points. Site Recovery replicates workloads and orchestrates a disaster-recovery failover.'],
  ['Zones vs sets', 'REGIONAL DATACENTERS ≠ FAULT DOMAINS', 'Zones provide physically separate locations inside a region. Sets distribute VMs across fault and update domains.'],
  ['Metrics vs logs', 'TIME SERIES ≠ QUERYABLE RECORDS', 'Metrics are fast numeric measurements. Logs provide richer event data and KQL-based analysis.'],
  ['Peering', 'CONNECTED ≠ TRANSITIVE', 'VNet peering connects two VNets but does not automatically route through a third. Transit needs an explicit design.'],
  ['Locks', 'DELETE PROTECTION ≠ SECURITY', 'A lock helps prevent deletion or changes; it does not grant access or replace RBAC and Policy.'],
  ['SAS', 'NARROW TOKEN ≠ ACCOUNT KEY', 'Choose scope, permissions, and expiry deliberately. An account key is broad and long-lived.'],
  ['Health probes', 'BACKEND EXISTS ≠ BACKEND HEALTHY', 'A load balancer routes only to healthy backends. Check probe protocol, port, path, and the rules allowing the probe.']
];

function renderDomains() {
  $('#domain-grid').innerHTML = domains.map((d) => `<article class="domain-card"><span class="domain-number">${d.number} / ${d.weight}</span><h3>${d.title}</h3><p>${d.copy}</p><footer><a href="${d.doc}" target="_blank" rel="noreferrer">Official docs ↗</a></footer></article>`).join('');
}

function planKey(planId, index) { return `az104-plan-${planId}-${index}`; }
function renderPlan(planId = 30) {
  const plan = plans[planId];
  $('#plan-content').innerHTML = `<div class="plan-meta"><span class="meta-pill">${plan.pace}</span><span class="meta-pill muted">${plan.label}</span><span class="mono">${plan.summary}</span></div><div class="plan-weeks">${plan.weeks.map((week, index) => `<article class="plan-week"><h3>${week.title}</h3><p>${week.name}</p>${week.tasks.map((task) => `<label class="plan-task"><input type="checkbox" data-plan-key="${planKey(planId, index)}" /> <span>${task}</span></label>`).join('')}</article>`).join('')}</div>`;
  $$('[data-plan-key]').forEach((input) => { input.checked = localStorage.getItem(input.dataset.planKey) === '1'; input.addEventListener('change', () => { localStorage.setItem(input.dataset.planKey, input.checked ? '1' : '0'); updateProgress(); }); });
}

function renderTraps() {
  $('#trap-grid').innerHTML = trapCards.map(([title, pair, copy]) => `<article class="trap-card"><h3>${title}</h3><div class="trap-pair">${pair}</div><p>${copy}</p></article>`).join('');
}

function flipFlashcard(card) {
  const flipped = card.classList.toggle('is-flipped');
  card.setAttribute('aria-expanded', String(flipped));
  $('.flashcard-flip', card).textContent = flipped ? 'Flip back ↻' : 'Flip card ↗';
}

function renderFlashcards(filter = 'all') {
  const visible = flashcards.filter((card) => filter === 'all' || card.domain === filter);
  $('#flash-counter').textContent = `${visible.length} visual card${visible.length === 1 ? '' : 's'}`;
  $('#flashcard-grid').innerHTML = visible.map((card, index) => `<article class="flashcard" tabindex="0" role="button" aria-expanded="false" data-flashcard="${index}"><div class="flashcard-inner"><div class="flashcard-face flashcard-front"><div class="flashcard-top"><span class="flash-domain">${domainLabels[card.domain]}</span><span class="flash-number">${String(index + 1).padStart(2, '0')}</span></div><h3>${card.title}</h3><div class="flash-visual">${card.visual}</div><button class="flashcard-flip" type="button">Flip card ↗</button></div><div class="flashcard-face flashcard-back"><div class="flashcard-top"><span class="flash-domain">${domainLabels[card.domain]} / TAKEAWAY</span><span class="flash-number">${String(index + 1).padStart(2, '0')}</span></div><h3>${card.title}</h3><div class="flash-definition"><span class="flash-label">REMEMBER</span><p>${card.definition}</p></div><div class="flash-cue"><span class="flash-label">EXAM CUE</span><p>${card.cue}</p></div><a class="flash-source" href="${card.source}" target="_blank" rel="noreferrer">Read official docs ↗</a><button class="flashcard-flip" type="button">Flip back ↻</button></div></div></article>`).join('');
  $$('.flashcard-flip').forEach((button) => button.addEventListener('click', (event) => { event.stopPropagation(); flipFlashcard(button.closest('.flashcard')); }));
  $$('.flashcard').forEach((card) => {
    card.addEventListener('click', () => flipFlashcard(card));
    card.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); flipFlashcard(card); } });
  });
}

function renderQuestions(filter = 'all') {
  $('#question-list').innerHTML = questions.map((item, index) => {
    const classes = [item.tag === 'case' ? 'case' : '', item.tag === 'trap' ? 'trap' : '', item.difficulty === 'hard' ? 'advanced' : ''].filter(Boolean).join(' ');
    const visible = filter === 'all' || (filter === 'advanced' ? item.difficulty === 'hard' : item.tag === filter);
    const hidden = !visible;
    const inputType = item.multi ? 'checkbox' : 'radio';
    const tagLabel = item.tag === 'case' ? 'CASE STUDY' : item.tag === 'trap' ? 'TRAP CHECK' : '';
    return `<article class="question-card ${hidden ? 'is-hidden' : ''}" data-question-id="${item.id}" data-tag="${item.tag || ''}"><div class="question-head"><span class="q-number">Q${String(index + 1).padStart(2, '0')} · ${domainLabels[item.domain]}</span>${tagLabel ? `<span class="q-tag ${classes}">${tagLabel}</span>` : ''}${item.difficulty === 'hard' ? '<span class="q-tag advanced">ADVANCED</span>' : ''}</div>${item.scenario ? `<p class="scenario"><strong>Scenario</strong><br />${item.scenario}</p>` : ''}${item.visual ? `<div class="question-visual">${item.visual}</div>` : ''}<h3>${item.q}${item.multi ? ' <span class="mono">(Select all that apply)</span>' : ''}</h3><div class="answer-options">${item.opts.map((option, optionIndex) => `<label class="answer-option"><input type="${inputType}" name="q-${item.id}" value="${optionIndex}" /> <span>${option}</span></label>`).join('')}</div><div class="question-footer"><button class="check-answer" data-check="${item.id}">Check answer</button><span class="answer-status" aria-live="polite"></span></div><div class="rationale"><strong>Why:</strong> ${item.explain} <a href="${item.source}" target="_blank" rel="noreferrer">Read the official docs ↗</a></div></article>`;
  }).join('');
  $$('[data-check]').forEach((button) => button.addEventListener('click', () => checkQuestion(Number(button.dataset.check))));
  restoreQuiz();
}

function checkQuestion(id) {
  const item = questions.find((question) => question.id === id);
  const card = $(`[data-question-id="${id}"]`);
  const selected = $$(`input[name="q-${id}"]:checked`, card).map((input) => Number(input.value)).sort();
  const expected = [...item.answer].sort();
  const status = $('.answer-status', card);
  const correct = JSON.stringify(selected) === JSON.stringify(expected);
  if (!selected.length) { status.textContent = 'Choose an answer first.'; status.className = 'answer-status wrong'; return; }
  $$('.answer-option', card).forEach((option, index) => { option.classList.remove('is-correct', 'is-wrong', 'is-reveal'); if (expected.includes(index)) option.classList.add(correct ? 'is-correct' : 'is-reveal'); else if (selected.includes(index)) option.classList.add('is-wrong'); });
  status.textContent = correct ? correctMessage(item) : 'Not quite — review the rationale.';
  status.className = `answer-status ${correct ? 'correct' : 'wrong'}`;
  $('.rationale', card).classList.add('is-visible');
  $$('.answer-option input', card).forEach((input) => { input.disabled = true; });
  $(`[data-check="${id}"]`, card).disabled = true;
  localStorage.setItem(`az104-answer-${id}`, JSON.stringify({ selected, correct }));
  updateScore();
}

function restoreQuiz() {
  questions.forEach((item) => { const saved = localStorage.getItem(`az104-answer-${item.id}`); if (!saved) return; try { const result = JSON.parse(saved); const card = $(`[data-question-id="${item.id}"]`); result.selected.forEach((value) => { const input = $(`input[value="${value}"]`, card); if (input) input.checked = true; }); checkQuestion(item.id); } catch (error) { localStorage.removeItem(`az104-answer-${item.id}`); } });
}

function updateScore() {
  const answered = questions.filter((item) => localStorage.getItem(`az104-answer-${item.id}`)).length;
  const correct = questions.filter((item) => { const saved = localStorage.getItem(`az104-answer-${item.id}`); return saved && JSON.parse(saved).correct; }).length;
  $('#quiz-score').textContent = `${answered} answered · ${answered ? Math.round((correct / answered) * 100) : 0}%`;
  updateProgress();
}

function updateProgress() {
  const planChecks = $$('[data-plan-key]').filter((input) => input.checked).length;
  const totalPlanChecks = $$('[data-plan-key]').length || 24;
  const answered = questions.filter((item) => localStorage.getItem(`az104-answer-${item.id}`)).length;
  const percent = Math.round(((planChecks / totalPlanChecks) * 0.45 + (answered / questions.length) * 0.55) * 100);
  $('#hero-progress').textContent = `${percent}%`;
  $('#hero-progress-bar').style.width = `${percent}%`;
}

function resetQuiz() {
  questions.forEach((item) => localStorage.removeItem(`az104-answer-${item.id}`));
  renderQuestions($('.filter-button.is-active').dataset.filter);
  updateScore();
}

function updateThemeButton() {
  const dark = document.body.classList.contains('dark-mode');
  $('#theme-toggle').setAttribute('aria-pressed', String(dark));
  $('#theme-toggle').setAttribute('aria-label', dark ? 'Switch to light mode' : 'Switch to dark mode');
  $('.theme-icon', $('#theme-toggle')).textContent = dark ? '☀' : '☾';
  $('.theme-label', $('#theme-toggle')).textContent = dark ? 'Light mode' : 'Dark mode';
}

if (localStorage.getItem('az104-theme') === 'dark') document.body.classList.add('dark-mode');
updateThemeButton();
$('#theme-toggle').addEventListener('click', () => { const dark = !document.body.classList.contains('dark-mode'); document.body.classList.toggle('dark-mode', dark); localStorage.setItem('az104-theme', dark ? 'dark' : 'light'); updateThemeButton(); });

renderDomains();
renderPlan(30);
renderTraps();
renderFlashcards();
renderQuestions();
updateScore();

$$('.plan-tab').forEach((tab) => tab.addEventListener('click', () => { $$('.plan-tab').forEach((button) => { button.classList.remove('is-active'); button.setAttribute('aria-selected', 'false'); }); tab.classList.add('is-active'); tab.setAttribute('aria-selected', 'true'); renderPlan(Number(tab.dataset.plan)); updateProgress(); }));
$$('.filter-button').forEach((button) => button.addEventListener('click', () => { $$('.filter-button').forEach((filter) => filter.classList.remove('is-active')); button.classList.add('is-active'); renderQuestions(button.dataset.filter); }));
$$('.flash-filter').forEach((button) => button.addEventListener('click', () => { $$('.flash-filter').forEach((filter) => filter.classList.remove('is-active')); button.classList.add('is-active'); renderFlashcards(button.dataset.flashFilter); }));
$('#reset-quiz').addEventListener('click', resetQuiz);
window.addEventListener('storage', updateProgress);
