const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

document.querySelectorAll('[data-scroll]').forEach((button) => button.addEventListener('click', () => $(button.dataset.scroll)?.scrollIntoView({ behavior: 'smooth' })));

const docs = {
  identity: 'https://learn.microsoft.com/en-us/azure/role-based-access-control/overview',
  policy: 'https://learn.microsoft.com/en-us/azure/governance/policy/overview',
  storage: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview',
  blob: 'https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview',
  sas: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview',
  files: 'https://learn.microsoft.com/en-us/azure/storage/files/storage-files-introduction',
  bicep: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview',
  vm: 'https://learn.microsoft.com/en-us/azure/virtual-machines/overview',
  appservice: 'https://learn.microsoft.com/en-us/azure/app-service/overview',
  containers: 'https://learn.microsoft.com/en-us/azure/container-instances/container-instances-overview',
  vnet: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview',
  nsg: 'https://learn.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview',
  private: 'https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-overview',
  lb: 'https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-overview',
  monitor: 'https://learn.microsoft.com/en-us/azure/azure-monitor/overview',
  logs: 'https://learn.microsoft.com/en-us/azure/azure-monitor/logs/log-query-overview',
  backup: 'https://learn.microsoft.com/en-us/azure/backup/backup-overview',
  siteRecovery: 'https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-overview'
};

const domains = [
  { number: '01', title: 'Identity & governance', weight: '20–25%', copy: 'Entra objects, RBAC, Policy, subscriptions, locks, tags, budgets, and management groups.', doc: docs.identity },
  { number: '02', title: 'Storage', weight: '15–20%', copy: 'Secure, resilient data with storage accounts, SAS, Blob, Azure Files, lifecycle, and replication.', doc: docs.storage },
  { number: '03', title: 'Compute', weight: '20–25%', copy: 'Deploy and operate VMs, scale sets, containers, App Service, TLS, slots, and automation.', doc: docs.vm },
  { number: '04', title: 'Networking', weight: '15–20%', copy: 'Design connected VNets with NSGs, peering, endpoints, DNS, routes, Bastion, and load balancing.', doc: docs.vnet },
  { number: '05', title: 'Monitor & maintain', weight: '10–15%', copy: 'Turn telemetry into action with Monitor, Network Watcher, Backup, and Site Recovery.', doc: docs.monitor }
];

const plans = {
  30: {
    pace: '60–90 MIN / DAY', label: 'FOCUSED SPRINT', summary: 'Four phases. Learn the control, practice the decision, then simulate the exam.',
    weeks: [
      { title: 'Days 01–07', name: 'Foundation + identity', tasks: ['Review exam format, scoring, and Azure hierarchy', 'Create Entra users/groups; practice RBAC scopes', 'Study Policy, locks, tags, budgets, and management groups'] },
      { title: 'Days 08–14', name: 'Storage + compute', tasks: ['Compare redundancy, SAS, keys, and identity-based access', 'Build the VM/App Service/container decision tree', 'Read Bicep and ARM deployment dependencies'] },
      { title: 'Days 15–21', name: 'Networking + operations', tasks: ['Draw VNets, NSGs, routes, peering, and endpoints', 'Compare DNS and load-balancing choices', 'Query Monitor logs; map Backup vs Site Recovery'] },
      { title: 'Days 22–30', name: 'Scenario sprint', tasks: ['Complete two domain-filtered practice rounds', 'Review traps and build a one-page gap sheet', 'Take a timed mixed test; revisit every miss'] }
    ]
  },
  90: {
    pace: '30–60 MIN / DAY', label: 'STEADY BUILD', summary: 'Twelve weeks with room for repetition: understand, operate, troubleshoot, and test.',
    weeks: [
      { title: 'Weeks 01–03', name: 'Azure + identity', tasks: ['Refresh Azure architecture and resource hierarchy', 'Work through Entra users, groups, licenses, SSPR, and guests', 'Practice RBAC inheritance and Policy evaluation'] },
      { title: 'Weeks 04–06', name: 'Storage + compute', tasks: ['Master storage security, redundancy, tiers, and data protection', 'Compare VM disks, availability, scale sets, and moves', 'Study App Service, containers, slots, TLS, and Bicep'] },
      { title: 'Weeks 07–09', name: 'Networking', tasks: ['Design a hub/spoke VNet with peering and UDRs', 'Drill NSG evaluation, private endpoints, and Bastion', 'Compare DNS, Load Balancer, Application Gateway, and probes'] },
      { title: 'Weeks 10–12', name: 'Operate + exam mode', tasks: ['Build Monitor/KQL, alert, Backup, and Site Recovery notes', 'Complete three mixed practice rounds and all case studies', 'Take two timed simulations; close gaps from explanations'] }
    ]
  }
};

const questions = [
  { id: 1, domain: 'identity', q: 'You need to give a team read-only access to every resource in one resource group, but no access to other groups. Which role and scope should you use?', opts: ['Reader at the resource-group scope', 'Contributor at the subscription scope', 'Owner at the resource scope', 'User Access Administrator at the management-group scope'], answer: [0], explain: '<strong>Reader at the resource-group scope</strong> grants read access to resources in that group and inherits downward without granting changes.', source: docs.identity },
  { id: 2, domain: 'identity', tag: 'trap', q: 'A user can open a storage account in the portal but cannot list blobs. Which distinction best explains this?', opts: ['Portal access is always equivalent to blob data access', 'Management-plane RBAC and data-plane permissions are separate', 'The storage account must be in the same region as the user', 'The user needs a resource lock removed'], answer: [1], explain: '<strong>Management-plane RBAC and data-plane permissions are separate.</strong> A role such as Reader can inspect the resource while a Blob Data Reader role is needed to read blob contents.', source: docs.identity },
  { id: 3, domain: 'identity', q: 'Which identity type is intended for an application that needs to access Azure resources without storing credentials?', opts: ['Managed identity', 'Guest user', 'Distribution group', 'Resource lock'], answer: [0], explain: '<strong>Managed identity</strong> lets Azure manage the service principal credentials and works with Microsoft Entra authentication.', source: 'https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview' },
  { id: 4, domain: 'identity', tag: 'case', scenario: 'Contoso has a central platform subscription and three application subscriptions. Security requires that every storage account disallow public network access. Application teams must still deploy resources.', q: 'What should the administrator use to enforce the storage network requirement across all three subscriptions?', opts: ['An Azure Policy assignment at a management group', 'A resource lock on each storage account', 'A Reader role at the platform subscription', 'A tag named publicNetworkAccess=false'], answer: [0], explain: '<strong>An Azure Policy assignment at a management group</strong> can evaluate and deny or audit configurations across descendant subscriptions. Tags and locks do not enforce property values.', source: docs.policy },
  { id: 5, domain: 'identity', q: 'Which feature prevents accidental deletion of a resource while still allowing authorized configuration changes?', opts: ['CanNotDelete resource lock', 'ReadOnly resource lock', 'Azure Policy audit effect', 'Reader role'], answer: [0], explain: 'A <strong>CanNotDelete</strong> lock prevents deletion while allowing writes. ReadOnly would also block configuration changes.', source: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources' },
  { id: 6, domain: 'identity', q: 'Which Azure hierarchy level is designed to organize subscriptions and apply governance across them?', opts: ['Management group', 'Availability set', 'Resource group', 'Virtual network'], answer: [0], explain: 'A <strong>management group</strong> sits above subscriptions and provides a scope for policy and RBAC inheritance.', source: 'https://learn.microsoft.com/en-us/azure/governance/management-groups/overview' },
  { id: 7, domain: 'identity', q: 'A company wants to require a cost-center tag on new resources but allow deployments to continue while compliance is measured. Which Policy effect fits?', opts: ['Audit', 'Deny', 'DeployIfNotExists', 'Disabled'], answer: [0], explain: '<strong>Audit</strong> records noncompliant resources without blocking the deployment. Deny would enforce the requirement immediately.', source: docs.policy },
  { id: 8, domain: 'identity', tag: 'trap', q: 'A budget alert has fired. What does that alert do by itself?', opts: ['Stops all resources in the subscription', 'Deletes the most expensive resource', 'Notifies configured recipients; it does not automatically stop spending', 'Changes the subscription to free tier'], answer: [2], explain: 'A budget alert <strong>notifies configured recipients</strong>. It is not an automatic spending cap or shutdown mechanism.', source: 'https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/tutorial-acm-create-budgets' },
  { id: 9, domain: 'identity', q: 'What is the least-privilege role for assigning roles to other principals without managing all resources?', opts: ['User Access Administrator', 'Reader', 'Storage Account Contributor', 'Billing Reader'], answer: [0], explain: '<strong>User Access Administrator</strong> manages access assignments. It is distinct from a resource-management role such as Contributor.', source: docs.identity },
  { id: 10, domain: 'identity', tag: 'case', scenario: 'A contractor from another organization needs temporary access to review a resource group. The contractor must sign in with their existing organization account.', q: 'Which object should you invite to the tenant?', opts: ['A Microsoft Entra B2B guest user', 'A managed identity', 'A service principal with a client secret', 'A dynamic device group'], answer: [0], explain: 'A <strong>Microsoft Entra B2B guest user</strong> can authenticate with the external organization while receiving scoped access in your tenant.', source: 'https://learn.microsoft.com/en-us/entra/external-id/what-is-b2b' },
  { id: 11, domain: 'identity', q: 'Which feature allows users to reset their own passwords after verification?', opts: ['Self-service password reset (SSPR)', 'Azure Advisor', 'Azure Bastion', 'Resource Graph'], answer: [0], explain: '<strong>SSPR</strong> lets users reset or change passwords after the configured authentication methods and licensing requirements are satisfied.', source: 'https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-howitworks' },
  { id: 12, domain: 'identity', tag: 'trap', q: 'A role assigned at the subscription scope normally applies to which resources?', opts: ['Only the subscription object', 'All descendant resource groups and resources', 'Only resources created after the assignment', 'Only Microsoft Entra objects'], answer: [1], explain: 'RBAC assignments <strong>inherit down the hierarchy</strong> from subscription to resource groups and resources unless a more specific restriction applies.', source: docs.identity },

  { id: 13, domain: 'storage', q: 'Which storage redundancy option replicates synchronously across availability zones in the primary region?', opts: ['ZRS', 'LRS', 'GRS', 'RA-GRS'], answer: [0], explain: '<strong>ZRS</strong> synchronously replicates data across availability zones in the primary region. GRS adds asynchronous replication to a secondary region.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy' },
  { id: 14, domain: 'storage', tag: 'trap', q: 'Which credential is most appropriate when an application needs time-limited, narrow access to a container?', opts: ['Account key shared indefinitely', 'A SAS token scoped to the container with required permissions and expiry', 'The subscription owner role', 'A resource lock'], answer: [1], explain: 'A <strong>scoped SAS token</strong> limits resource, permissions, and time. Account keys are broad credentials and should not be distributed to applications.', source: docs.sas },
  { id: 15, domain: 'storage', q: 'Which Blob access tier is intended for data that is rarely accessed but must be available online with lower storage cost?', opts: ['Hot', 'Cool', 'Archive', 'Premium page blob'], answer: [1], explain: '<strong>Cool</strong> is an online tier for infrequently accessed data. Archive has offline rehydration latency and different access economics.', source: docs.blob },
  { id: 16, domain: 'storage', tag: 'case', scenario: 'An analytics team stores raw logs. Files older than 90 days should move to Cool, older than 365 days should be deleted, and the team does not want a scheduled script.', q: 'Which Azure capability should implement this requirement?', opts: ['Blob lifecycle management policy', 'Azure File Sync', 'A storage account firewall rule', 'A recovery plan'], answer: [0], explain: '<strong>Blob lifecycle management</strong> applies rule-based tiering and deletion to blob data based on age and other conditions.', source: 'https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview' },
  { id: 17, domain: 'storage', q: 'Which tool is designed to copy data to and from Azure Storage from the command line with high performance?', opts: ['AzCopy', 'Azure Policy', 'Azure Migrate', 'Network Watcher'], answer: [0], explain: '<strong>AzCopy</strong> is the command-line utility for copying blobs and files to or from Azure Storage.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10' },
  { id: 18, domain: 'storage', q: 'What does blob versioning primarily provide?', opts: ['A history of blob versions that can be accessed or restored', 'A private endpoint for the storage account', 'Synchronous cross-region replication', 'A replacement for authorization'], answer: [0], explain: '<strong>Blob versioning</strong> automatically preserves prior versions when a blob is modified or deleted, supporting recovery and tracking.', source: 'https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview' },
  { id: 19, domain: 'storage', tag: 'trap', q: 'Which statement about a storage account firewall is correct?', opts: ['It grants a user permission to read blob data', 'It restricts network access; identity or token authorization is still required', 'It encrypts every blob with a customer-managed key', 'It replaces private endpoints'], answer: [1], explain: 'A firewall controls <strong>network reachability</strong>. Authorization is a separate concern handled by Entra roles, SAS, or keys.', source: 'https://learn.microsoft.com/en-us/azure/storage/common/storage-network-security' },
  { id: 20, domain: 'storage', q: 'Which service provides SMB file shares that can be mounted by Azure and on-premises clients?', opts: ['Azure Files', 'Blob Storage', 'Table Storage', 'Queue Storage'], answer: [0], explain: '<strong>Azure Files</strong> provides managed file shares over SMB (and NFS for supported configurations).', source: docs.files },
  { id: 21, domain: 'storage', tag: 'case', scenario: 'A web app should access one blob for 15 minutes. It must not know the storage account key and must not write other blobs.', q: 'Which design best meets the requirement?', opts: ['Use a user delegation SAS with read permission, blob scope, and a 15-minute expiry', 'Use the storage account key in an app setting', 'Assign Owner at the subscription scope', 'Make the container public'], answer: [0], explain: 'A <strong>user delegation SAS</strong> avoids account keys and can constrain the token to one blob, read-only, for a short period.', source: docs.sas },
  { id: 22, domain: 'storage', q: 'Which option protects a file share from accidental deletion by retaining deleted files for a configured period?', opts: ['Azure Files soft delete', 'Blob index tags', 'Object replication', 'Storage Explorer'], answer: [0], explain: '<strong>Azure Files soft delete</strong> retains deleted shares for recovery during the configured retention period.', source: 'https://learn.microsoft.com/en-us/azure/storage/files/storage-files-recovery' },
  { id: 23, domain: 'storage', q: 'What is the primary purpose of object replication for Blob Storage?', opts: ['Asynchronously replicate block blobs between storage accounts', 'Provide an SMB mount point', 'Force all writes through a private endpoint', 'Convert blobs to archive tier'], answer: [0], explain: '<strong>Object replication</strong> asynchronously copies block blobs between a source and destination account according to replication rules.', source: 'https://learn.microsoft.com/en-us/azure/storage/blobs/object-replication-overview' },
  { id: 24, domain: 'storage', tag: 'trap', q: 'Which statement correctly distinguishes a stored access policy from a SAS?', opts: ['A stored access policy is only available for the subscription', 'A stored access policy can centralize constraints for certain service SAS tokens', 'A SAS always grants full account access', 'A stored access policy encrypts the storage account'], answer: [1], explain: 'A <strong>stored access policy</strong> can define or revoke shared constraints for supported service SAS tokens at the container or share level.', source: docs.sas },

  { id: 25, domain: 'compute', q: 'Which deployment artifact is the Azure-native, declarative language that compiles to ARM templates?', opts: ['Bicep', 'KQL', 'YAML pipeline only', 'PowerShell DSC'], answer: [0], explain: '<strong>Bicep</strong> is a declarative language for Azure resource deployment and compiles to ARM template JSON.', source: docs.bicep },
  { id: 26, domain: 'compute', tag: 'trap', q: 'What is the key distinction between an availability zone and an availability set?', opts: ['Zones are separate physical locations within a region; sets distribute VMs across fault and update domains', 'Sets always span regions; zones never do', 'Zones are a billing scope; sets are an RBAC scope', 'They are interchangeable names for the same feature'], answer: [0], explain: '<strong>Availability zones</strong> are physically separate datacenters in a region. Availability sets distribute VMs within a datacenter across fault and update domains.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machines/availability' },
  { id: 27, domain: 'compute', q: 'Which disk type is the default OS disk option for most general-purpose Azure VMs?', opts: ['Managed disk', 'Ephemeral local cache only', 'Azure Files share', 'Blob container'], answer: [0], explain: '<strong>Managed disks</strong> are Azure-managed virtual disks used by VMs and available in several performance tiers.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview' },
  { id: 28, domain: 'compute', tag: 'case', scenario: 'A stateless API has variable demand. It should scale horizontally based on CPU and deploy a new version gradually without new infrastructure.', q: 'Which combination is most appropriate?', opts: ['App Service autoscale and a deployment slot', 'A single VM and an availability set', 'Azure Files snapshots and a SAS token', 'A Recovery Services vault and a UDR'], answer: [0], explain: '<strong>App Service autoscale and a deployment slot</strong> address horizontal scaling and controlled version rollout for an App Service app.', source: docs.appservice },
  { id: 29, domain: 'compute', q: 'What does changing a VM size generally change?', opts: ['The VM compute capacity and available attached data-disk limits', 'The tenant directory and RBAC assignments', 'The region of the VM automatically', 'The contents of the OS disk'], answer: [0], explain: 'Changing VM size changes <strong>compute capacity</strong> such as CPU and memory and may affect disk/network limits; it does not move or rewrite the OS disk.', source: docs.vm },
  { id: 30, domain: 'compute', q: 'Which service is optimized for running a single container or small container group without managing VMs?', opts: ['Azure Container Instances', 'Azure Virtual Desktop', 'Azure DNS', 'Azure Load Testing'], answer: [0], explain: '<strong>Azure Container Instances</strong> provides serverless container execution without VM management.', source: docs.containers },
  { id: 31, domain: 'compute', tag: 'trap', q: 'An App Service plan is scaled up. What does that mean?', opts: ['Changing the pricing tier or instance size/capabilities', 'Adding more instances only', 'Creating a new deployment slot', 'Moving the app to another subscription'], answer: [0], explain: '<strong>Scale up</strong> changes the plan tier or instance size. Scale out adds instances.', source: docs.appservice },
  { id: 32, domain: 'compute', tag: 'case', scenario: 'A team needs to deploy the same network, storage, and app resources repeatedly with parameterized names and SKU values.', q: 'Which approach best supports repeatable declarative deployments?', opts: ['A Bicep file with parameters and modules', 'Manual portal clicks recorded in a document', 'A storage SAS token', 'A Network Security Group rule'], answer: [0], explain: '<strong>Bicep with parameters and modules</strong> expresses repeatable infrastructure and keeps environment-specific values separate from resource definitions.', source: docs.bicep },
  { id: 33, domain: 'compute', q: 'What is the purpose of a VM Scale Set?', opts: ['Manage and autoscale a group of load-balanced VMs', 'Store multiple copies of a blob', 'Provide DNS name resolution', 'Assign Entra licenses'], answer: [0], explain: 'A <strong>VM Scale Set</strong> manages a set of load-balanced, similarly configured VMs and can scale the instance count.', source: 'https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview' },
  { id: 34, domain: 'compute', q: 'Which App Service feature lets you validate a release in an isolated environment and swap it into production?', opts: ['Deployment slot', 'App Service plan', 'Access restriction rule', 'Custom domain'], answer: [0], explain: 'A <strong>deployment slot</strong> provides a separate app instance for testing and supports swapping into production.', source: docs.appservice },
  { id: 35, domain: 'compute', tag: 'trap', q: 'Which statement about moving an Azure resource is safest?', opts: ['Every resource can move across subscriptions and regions', 'Move support is resource-specific; region moves often require a different migration pattern', 'A resource lock makes a move possible', 'Changing a tag moves the resource'], answer: [1], explain: '<strong>Move support is resource-specific.</strong> Subscription/resource-group moves have documented dependencies, while regional moves commonly require redeployment or a migration workflow.', source: 'https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription' },
  { id: 36, domain: 'compute', q: 'Which App Service setting maps a custom hostname to an app?', opts: ['Custom domain', 'Deployment slot setting only', 'Private DNS zone link', 'VM extension'], answer: [0], explain: 'The <strong>Custom domain</strong> configuration maps a DNS name to an App Service and can be paired with a certificate for TLS.', source: docs.appservice },

  { id: 37, domain: 'network', q: 'Which resource defines an IP address range and contains subnets?', opts: ['Virtual network', 'Network security group', 'Route table', 'Public IP prefix'], answer: [0], explain: 'A <strong>virtual network</strong> defines the address space and contains one or more subnets.', source: docs.vnet },
  { id: 38, domain: 'network', tag: 'trap', q: 'What is true about VNet peering?', opts: ['It automatically provides transitive routing through a third peered VNet', 'It privately connects VNets, but peering alone is not transitive', 'It requires a public IP on every VM', 'It replaces all NSG rules'], answer: [1], explain: 'VNet peering provides private connectivity, but <strong>peering is not transitive</strong>. A hub may need routing/NVA design for transit.', source: docs.vnet },
  { id: 39, domain: 'network', q: 'Which rule is evaluated first in an NSG?', opts: ['The rule with the lowest priority number', 'The rule with the highest priority number', 'The newest rule', 'The rule closest to the VM in the portal'], answer: [0], explain: 'NSG rules are evaluated in ascending order, so the <strong>lowest priority number</strong> wins when a matching rule is found.', source: docs.nsg },
  { id: 40, domain: 'network', tag: 'case', scenario: 'A PaaS database must be reachable from an application subnet over a private IP. Public internet access must be disabled and the database DNS name should resolve privately.', q: 'Which design meets the requirement?', opts: ['Private endpoint plus a private DNS zone configuration', 'Service endpoint only with a public IP', 'A public Load Balancer in front of the database', 'A UDR that points to the internet'], answer: [0], explain: 'A <strong>private endpoint plus private DNS</strong> gives the PaaS resource a private IP and ensures the normal name resolves to that private address.', source: docs.private },
  { id: 41, domain: 'network', q: 'What does a user-defined route (UDR) allow you to control?', opts: ['The next hop for traffic in a subnet', 'The DNS record TTL for a zone', 'The number of VM instances', 'The blob access tier'], answer: [0], explain: 'A route table with <strong>UDRs</strong> can direct subnet traffic to a virtual appliance, virtual network gateway, internet, or another supported next hop.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-udr-overview' },
  { id: 42, domain: 'network', tag: 'trap', q: 'Which statement about service endpoints is correct?', opts: ['They give a PaaS service a private IP in your subnet', 'They extend a subnet identity to an Azure service and keep the service public endpoint', 'They are required for VNet peering', 'They encrypt all application payloads'], answer: [1], explain: 'A <strong>service endpoint</strong> enables subnet-based access to supported Azure services while the service endpoint remains public. A private endpoint uses a private IP.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview' },
  { id: 43, domain: 'network', q: 'Which Azure service provides managed RDP/SSH access to VMs without requiring public IPs on the VMs?', opts: ['Azure Bastion', 'Azure DNS', 'Azure Front Door', 'Azure Firewall Manager only'], answer: [0], explain: '<strong>Azure Bastion</strong> provides browser-based RDP/SSH through the Azure portal over TLS, allowing VMs to remain without public IPs.', source: 'https://learn.microsoft.com/en-us/azure/bastion/bastion-overview' },
  { id: 44, domain: 'network', tag: 'case', scenario: 'Two web VMs sit behind an internal load balancer. One VM is never receiving traffic. The backend pool is configured, but the health probe marks that VM unhealthy.', q: 'What should you inspect first?', opts: ['The probe protocol/port/path and whether the VM permits the probe', 'The storage account access tier', 'The Entra license assignment', 'The App Service deployment slot'], answer: [0], explain: 'A load balancer only sends new flows to healthy backends, so inspect the <strong>probe settings and backend response</strong>, plus NSG/firewall rules.', source: docs.lb },
  { id: 45, domain: 'network', q: 'Which service resolves names for Azure resources using a Microsoft-managed DNS service by default?', opts: ['Azure-provided DNS', 'Azure Backup', 'Application Gateway WAF', 'Azure Policy'], answer: [0], explain: '<strong>Azure-provided DNS</strong> is the default name-resolution service for VMs in a VNet; custom DNS can be configured when needed.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances' },
  { id: 46, domain: 'network', q: 'What is an application security group (ASG) primarily used for?', opts: ['Grouping VM network interfaces so NSG rules can express application roles', 'Storing TLS certificates', 'Replicating VNets across regions', 'Managing Azure subscriptions'], answer: [0], explain: 'An <strong>ASG</strong> groups network interfaces by application role, making NSG rules easier to read and maintain.', source: 'https://learn.microsoft.com/en-us/azure/virtual-network/application-security-groups' },
  { id: 47, domain: 'network', tag: 'trap', q: 'When evaluating effective NSG rules for a VM, what should you remember?', opts: ['Only the subnet NSG matters', 'Only the NIC NSG matters', 'Inbound rules can be affected by both subnet and NIC NSGs', 'NSGs are evaluated after the application receives traffic'], answer: [2], explain: 'For a VM, <strong>subnet and NIC NSGs</strong> both participate in the effective rule set. A deny at either applicable layer can block traffic.', source: docs.nsg },
  { id: 48, domain: 'network', q: 'Which load-balancing option operates at Layer 7 and can route HTTP traffic using URL paths?', opts: ['Application Gateway', 'Azure Load Balancer', 'VNet peering', 'NAT Gateway'], answer: [0], explain: '<strong>Application Gateway</strong> is a Layer 7 HTTP(S) load balancer with path-based routing. Azure Load Balancer is Layer 4.', source: 'https://learn.microsoft.com/en-us/azure/application-gateway/overview' },

  { id: 49, domain: 'monitor', q: 'Which Azure Monitor data type is best for a time-series value such as VM CPU percentage?', opts: ['Metric', 'Activity log only', 'Resource lock', 'Management group'], answer: [0], explain: 'A <strong>metric</strong> is a time-series numerical measurement such as CPU percentage and is suited to near-real-time alerting.', source: docs.monitor },
  { id: 50, domain: 'monitor', tag: 'trap', q: 'Which statement correctly distinguishes Azure metrics from logs?', opts: ['Metrics are numeric time-series; logs are richer event and text records queried in Log Analytics', 'Logs are always cheaper and real-time; metrics cannot alert', 'Metrics contain full queryable stack traces by default', 'They are two names for the same data'], answer: [0], explain: '<strong>Metrics are numeric time-series</strong>; logs provide richer records for analysis with KQL. Both can drive alerts, but their data and use cases differ.', source: docs.monitor },
  { id: 51, domain: 'monitor', q: 'Where are KQL queries commonly used to analyze Azure Monitor logs?', opts: ['A Log Analytics workspace', 'A resource lock', 'An availability set', 'A storage access key blade'], answer: [0], explain: 'Azure Monitor logs are queried in a <strong>Log Analytics workspace</strong> using Kusto Query Language (KQL).', source: docs.logs },
  { id: 52, domain: 'monitor', tag: 'case', scenario: 'An operations team wants a single notification when a production VM has high CPU for 10 minutes. The email should go to the on-call group.', q: 'Which configuration should you create?', opts: ['Metric alert with a condition, action group, and appropriate evaluation window', 'Resource lock with a CanNotDelete setting', 'A storage lifecycle rule', 'A user-defined route'], answer: [0], explain: 'A <strong>metric alert plus action group</strong> evaluates the CPU condition and sends the notification to the on-call recipients.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-overview' },
  { id: 53, domain: 'monitor', q: 'What is an action group?', opts: ['A reusable collection of notification and automation actions for alerts', 'A group of VMs in an availability set', 'A set of RBAC roles', 'A collection of storage containers'], answer: [0], explain: 'An <strong>action group</strong> centralizes actions such as email, SMS, webhook, Logic App, or automation runbook for alert rules.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/action-groups' },
  { id: 54, domain: 'monitor', tag: 'trap', q: 'Which service is intended to restore backed-up data after accidental deletion, while Site Recovery primarily addresses what scenario?', opts: ['Backup restores data; Site Recovery orchestrates disaster recovery/failover', 'Backup changes NSG priorities; Site Recovery manages RBAC', 'Backup provides DNS; Site Recovery provides SAS', 'They are identical services'], answer: [0], explain: '<strong>Azure Backup</strong> protects and restores data. <strong>Site Recovery</strong> orchestrates replication and failover for business continuity.', source: docs.backup },
  { id: 55, domain: 'monitor', q: 'What is the purpose of a Recovery Services vault?', opts: ['Store backup data and recovery points for supported workloads', 'Host a VNet subnet', 'Issue Entra tokens', 'Route internet traffic'], answer: [0], explain: 'A <strong>Recovery Services vault</strong> stores backup data and recovery points for supported Azure Backup and Site Recovery scenarios.', source: docs.backup },
  { id: 56, domain: 'monitor', tag: 'case', scenario: 'A regional outage affects an Azure VM. The business has a recovery plan that replicates the VM to a secondary region and has tested failover.', q: 'Which operation should the administrator perform to bring the workload up in the secondary region?', opts: ['Fail over the protected item in Azure Site Recovery', 'Restore a deleted blob version', 'Change the VM availability set', 'Run a storage lifecycle policy'], answer: [0], explain: 'A configured Site Recovery plan uses <strong>failover</strong> to activate the replicated workload in the secondary region.', source: docs.siteRecovery },
  { id: 57, domain: 'monitor', q: 'Which Network Watcher capability helps test whether a VM can reach a destination on a specific port?', opts: ['Connection troubleshoot', 'Blob inventory', 'Cost analysis', 'Access reviews'], answer: [0], explain: '<strong>Connection troubleshoot</strong> tests connectivity between a source and destination and helps identify the failing component.', source: 'https://learn.microsoft.com/en-us/azure/network-watcher/connection-troubleshoot-overview' },
  { id: 58, domain: 'monitor', q: 'Which Azure Monitor feature provides curated telemetry for services such as VMs and storage accounts?', opts: ['Insights', 'Resource locks', 'Management groups', 'SAS'], answer: [0], explain: '<strong>Insights</strong> provide curated monitoring views and telemetry for supported Azure resources.', source: 'https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-overview' },
  { id: 59, domain: 'monitor', tag: 'trap', q: 'A log alert has a query that returns no rows. What is the most useful first check?', opts: ['Verify the resource is sending the relevant category to the workspace and the query time range is correct', 'Add an Owner role to every user', 'Change the VM size', 'Create a resource lock'], answer: [0], explain: 'Start with telemetry plumbing: <strong>diagnostic settings, destination workspace, table/category, and time range</strong>. An empty query cannot trigger the intended condition.', source: docs.logs },
  { id: 60, domain: 'monitor', tag: 'case', scenario: 'You need a weekly view of backup failures across several vaults and want the data retained for analysis rather than relying only on individual alert emails.', q: 'Which approach is most appropriate?', opts: ['Configure backup reporting/diagnostics and analyze the collected data in the reporting destination', 'Use a ReadOnly lock on each vault', 'Create a public IP for each vault', 'Move all vaults into one resource group'], answer: [0], explain: 'Centralized <strong>backup reporting and diagnostic data</strong> supports cross-vault analysis and retention beyond individual notifications.', source: 'https://learn.microsoft.com/en-us/azure/backup/monitor-azure-backup-with-azure-monitor' }
];

const domainLabels = { identity: 'IDENTITY', storage: 'STORAGE', compute: 'COMPUTE', network: 'NETWORKING', monitor: 'MONITORING' };
$('#case-count').textContent = questions.filter((question) => question.tag === 'case').length;
$('#trap-count').textContent = questions.filter((question) => question.tag === 'trap').length;
const trapCards = [
  ['RBAC vs data access', 'CONTROL PLANE ≠ DATA PLANE', 'Reader can open a resource; it does not automatically read the blobs, files, or secrets inside it. Match the role to the data plane.'],
  ['Policy vs RBAC', 'GOVERNANCE ≠ AUTHORIZATION', 'Policy evaluates resource state and can audit or deny. RBAC answers who may perform an action. They complement each other.'],
  ['Service vs private endpoint', 'PUBLIC ENDPOINT ≠ PRIVATE IP', 'A service endpoint keeps the service public while adding subnet identity. A private endpoint creates a NIC/private IP in your VNet.'],
  ['NSG priority', 'LOW NUMBER WINS', 'Rules are processed from lowest priority number upward. A broad allow placed before a specific deny can change the result.'],
  ['Scale up vs scale out', 'SIZE ≠ INSTANCES', 'Scale up changes the plan or VM size. Scale out adds instances. Look for “capacity” versus “number of copies.”'],
  ['Backup vs Site Recovery', 'RESTORE ≠ FAILOVER', 'Backup restores data from recovery points. Site Recovery replicates workloads and orchestrates a disaster-recovery failover.'],
  ['Zones vs sets', 'REGIONAL DATACENTERS ≠ FAULT DOMAINS', 'Zones provide physically separate locations inside a region. Sets distribute VMs across fault and update domains.'],
  ['Metrics vs logs', 'TIME SERIES ≠ QUERYABLE RECORDS', 'Metrics are fast numeric measurements. Logs provide richer event data and KQL-based analysis.'],
  ['Peering', 'CONNECTED ≠ TRANSITIVE', 'VNet peering connects two VNets but does not automatically route through a third. Transit needs an explicit design.'],
  ['Locks', 'DELETE PROTECTION ≠ SECURITY', 'A lock helps prevent deletion or changes; it does not grant access or replace RBAC and Policy.'],
  ['SAS', 'NARROW TOKEN ≠ ACCOUNT KEY', 'Choose scope, permissions, and expiry deliberately. An account key is broad and long-lived.'],
  ['Health probes', 'BACKEND EXISTS ≠ BACKEND HEALTHY', 'A load balancer routes only to healthy backends. Check probe protocol, port, path, and the rules allowing the probe.']
];

function renderDomains() {
  $('#domain-grid').innerHTML = domains.map((d) => `<article class="domain-card"><span class="domain-number">${d.number} / ${d.weight}</span><h3>${d.title}</h3><p>${d.copy}</p><footer><a href="${d.doc}" target="_blank" rel="noreferrer">Official docs ↗</a></footer></article>`).join('');
}

function planKey(planId, index) { return `az104-plan-${planId}-${index}`; }
function renderPlan(planId = 30) {
  const plan = plans[planId];
  $('#plan-content').innerHTML = `<div class="plan-meta"><span class="meta-pill">${plan.pace}</span><span class="meta-pill muted">${plan.label}</span><span class="mono">${plan.summary}</span></div><div class="plan-weeks">${plan.weeks.map((week, index) => `<article class="plan-week"><h3>${week.title}</h3><p>${week.name}</p>${week.tasks.map((task) => `<label class="plan-task"><input type="checkbox" data-plan-key="${planKey(planId, index)}" /> <span>${task}</span></label>`).join('')}</article>`).join('')}</div>`;
  $$('[data-plan-key]').forEach((input) => { input.checked = localStorage.getItem(input.dataset.planKey) === '1'; input.addEventListener('change', () => { localStorage.setItem(input.dataset.planKey, input.checked ? '1' : '0'); updateProgress(); }); });
}

function renderTraps() {
  $('#trap-grid').innerHTML = trapCards.map(([title, pair, copy]) => `<article class="trap-card"><h3>${title}</h3><div class="trap-pair">${pair}</div><p>${copy}</p></article>`).join('');
}

function renderQuestions(filter = 'all') {
  $('#question-list').innerHTML = questions.map((item, index) => {
    const classes = [item.tag === 'case' ? 'case' : '', item.tag === 'trap' ? 'trap' : ''].filter(Boolean).join(' ');
    const hidden = filter !== 'all' && item.tag !== filter;
    const inputType = item.multi ? 'checkbox' : 'radio';
    return `<article class="question-card ${hidden ? 'is-hidden' : ''}" data-question-id="${item.id}" data-tag="${item.tag || ''}"><div class="question-head"><span class="q-number">Q${String(index + 1).padStart(2, '0')} · ${domainLabels[item.domain]}</span>${item.tag ? `<span class="q-tag ${classes}">${item.tag === 'case' ? 'CASE STUDY' : 'TRAP CHECK'}</span>` : ''}</div>${item.scenario ? `<p class="scenario"><strong>Scenario</strong><br />${item.scenario}</p>` : ''}<h3>${item.q}${item.multi ? ' <span class="mono">(Select all that apply)</span>' : ''}</h3><div class="answer-options">${item.opts.map((option, optionIndex) => `<label class="answer-option"><input type="${inputType}" name="q-${item.id}" value="${optionIndex}" /> <span>${option}</span></label>`).join('')}</div><div class="question-footer"><button class="check-answer" data-check="${item.id}">Check answer</button><span class="answer-status" aria-live="polite"></span></div><div class="rationale"><strong>Why:</strong> ${item.explain} <a href="${item.source}" target="_blank" rel="noreferrer">Read the official docs ↗</a></div></article>`;
  }).join('');
  $$('[data-check]').forEach((button) => button.addEventListener('click', () => checkQuestion(Number(button.dataset.check))));
  restoreQuiz();
}

function checkQuestion(id) {
  const item = questions.find((question) => question.id === id);
  const card = $(`[data-question-id="${id}"]`);
  const selected = $$(`input[name="q-${id}"]:checked`, card).map((input) => Number(input.value)).sort();
  const expected = [...item.answer].sort();
  const status = $('.answer-status', card);
  const correct = JSON.stringify(selected) === JSON.stringify(expected);
  if (!selected.length) { status.textContent = 'Choose an answer first.'; status.className = 'answer-status wrong'; return; }
  $$('.answer-option', card).forEach((option, index) => { option.classList.remove('is-correct', 'is-wrong', 'is-reveal'); if (expected.includes(index)) option.classList.add(correct ? 'is-correct' : 'is-reveal'); else if (selected.includes(index)) option.classList.add('is-wrong'); });
  status.textContent = correct ? 'Correct — nice read.' : 'Not quite — review the rationale.';
  status.className = `answer-status ${correct ? 'correct' : 'wrong'}`;
  $('.rationale', card).classList.add('is-visible');
  $$('.answer-option input', card).forEach((input) => { input.disabled = true; });
  $(`[data-check="${id}"]`, card).disabled = true;
  localStorage.setItem(`az104-answer-${id}`, JSON.stringify({ selected, correct }));
  updateScore();
}

function restoreQuiz() {
  questions.forEach((item) => { const saved = localStorage.getItem(`az104-answer-${item.id}`); if (!saved) return; try { const result = JSON.parse(saved); const card = $(`[data-question-id="${item.id}"]`); result.selected.forEach((value) => { const input = $(`input[value="${value}"]`, card); if (input) input.checked = true; }); checkQuestion(item.id); } catch (error) { localStorage.removeItem(`az104-answer-${item.id}`); } });
}

function updateScore() {
  const answered = questions.filter((item) => localStorage.getItem(`az104-answer-${item.id}`)).length;
  const correct = questions.filter((item) => { const saved = localStorage.getItem(`az104-answer-${item.id}`); return saved && JSON.parse(saved).correct; }).length;
  $('#quiz-score').textContent = `${answered} answered · ${answered ? Math.round((correct / answered) * 100) : 0}%`;
  updateProgress();
}

function updateProgress() {
  const planChecks = $$('[data-plan-key]').filter((input) => input.checked).length;
  const totalPlanChecks = $$('[data-plan-key]').length || 24;
  const answered = questions.filter((item) => localStorage.getItem(`az104-answer-${item.id}`)).length;
  const percent = Math.round(((planChecks / totalPlanChecks) * 0.45 + (answered / questions.length) * 0.55) * 100);
  $('#hero-progress').textContent = `${percent}%`;
  $('#hero-progress-bar').style.width = `${percent}%`;
}

function resetQuiz() {
  questions.forEach((item) => localStorage.removeItem(`az104-answer-${item.id}`));
  renderQuestions($('.filter-button.is-active').dataset.filter);
  updateScore();
}

renderDomains();
renderPlan(30);
renderTraps();
renderQuestions();
updateScore();

$$('.plan-tab').forEach((tab) => tab.addEventListener('click', () => { $$('.plan-tab').forEach((button) => { button.classList.remove('is-active'); button.setAttribute('aria-selected', 'false'); }); tab.classList.add('is-active'); tab.setAttribute('aria-selected', 'true'); renderPlan(Number(tab.dataset.plan)); updateProgress(); }));
$$('.filter-button').forEach((button) => button.addEventListener('click', () => { $$('.filter-button').forEach((filter) => filter.classList.remove('is-active')); button.classList.add('is-active'); renderQuestions(button.dataset.filter); }));
$('#reset-quiz').addEventListener('click', resetQuiz);
window.addEventListener('storage', updateProgress);
